### ISSUE TITLE
can't access ubuntu after deployed 

### ISSUE THREAD

**Issue by mhost39** [threefoldtech/zos#1149]
in branch: development 

i deployed a network with
![image](https://user-images.githubusercontent.com/31102305/104457648-ffdac880-55b2-11eb-8828-1e644a131b32.png)

and i can ping 185.69.167.190

after that i deployed ubuntu with 
![image](https://user-images.githubusercontent.com/31102305/104457858-3d3f5600-55b3-11eb-8c0d-6b0640a294df.png)

when i try to access this ubuntu get not reachable 
![image](https://user-images.githubusercontent.com/31102305/104448910-74f3d100-55a6-11eb-9941-258ddbd707ec.png)

**Comment by LeeSmet** [comment]
So after debugging I've come to the following conclusion:

The access node is actually fine, but it can't get a handshake with the other nodes. On closer inspection, these other nodes seem to have an ipv6 address used in the wireguard config.

The wg process on these other nodes listens on the host namespace. tcp dumping br-pub shows that every now and then a udp packet comes in from the access point. There are no outgoing packets.

Pinging the IP6 of the access point, from the host of one of these nodes, shows that there is no connectivity.

All nodes seem to be dual NIC nodes. When checking the host namespace, we see that the IP used is attached to br-pub. However, it is also attached to the secondary NIC. Both interfaces share the same mac address (~not sure why this is, it does not seem like we set that explicitly~ this is expected behavior). When checking the routing table, we see that the route is duplicated for both interfaces:

![image](https://user-images.githubusercontent.com/22023708/104461481-ade47380-55af-11eb-96d7-9eb141c5851b.png)

checking which one is used for sending packets shows that it is actually the physical interface that is being used (or rather, the kernel _tries_ to use):

![image](https://user-images.githubusercontent.com/22023708/104461686-f1d77880-55af-11eb-875d-22286c2d3f5b.png)

This does not work since the interface is attached to the bridge. Deleting the routing rule for the physical interface so only the one over br-pub remains fixes connectivity.

All in all, the solution would be to disable the ipv6 on the master interface of br-pub, or rather, the interface which is plugged into br-pub, as for single NIC nodes, this will be a veth pair attached to the zos bridge. We obviously can't disable ipv6 on the zos bridge itself.

CC @delandtj

**Comment by LeeSmet** [comment]
On closer isnpection, a similar problem arises on single nic nodes. (see `8zPYak76CXcoZxRoJBjdU69kVjo7XYU1SFE2NEK4UMqn`). Both the zos bridge and br-pub have an ipv6 address in the same segment and conflicting duplicate routes for the segment. We can disable ipv6 on zos (so then we'd disable ipv6 on the master of br-pub), but I'm not sure if that is the proper solution here

EDIT: after another look, there are handshakes with other nodes which where fixed as described above. So its likely an issue with all other testnet nodes suffering from the same problem and this one not, as its running in single nic mode for some obscure reason

**Comment by ramezsaeed** [comment]
verified
