### ISSUE TITLE
invalid configured disk empty path

### ISSUE THREAD

**Issue by MohamedEssamAdawy** [threefoldtech/zos#1152]
I have deployed Kubernetes on devnet and was working until Thursday
Master workload: https://explorer.devnet.grid.tf/api/v1/reservations/workloads/18030
Worker workload: https://explorer.devnet.grid.tf/api/v1/reservations/workloads/18036

Yesterday It returns this error message: `invalid configured disk empty path '18030-1'` for the master node

**Comment by muhamadazmy** [comment]
here is what we think has happened:
- every day a janitor runs on the node to clean up some resources
- this janitor find the vdisks on the node then checks the explorer if there is an active and valid reservation with same id.
- if the explorer returns 404, or returns a reservation that has expired, then the janitor will take care to free the assigned resources.
- the current explorer code unfortunately, also returned 404 on other errors, so a network glitch or other issues regarding the database connection caused the explorer to return 404 which the janitor interpreted as the reservation does not exist, and deleted the disk

Fixed by https://github.com/threefoldtech/tfexplorer/pull/282
