### ISSUE TITLE
ZOS: optional Yggdrasil IP inside zos containers

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/zos#1168]

**Comment by LeeSmet** [comment]
In order to support yggdrasil in containers/vms, the following will be needed:

- If a container needs an yggdrasil IP, we need to create a second veth pair, attached in `br-pub` on one end, and in the container netns with the other end. This will essentially be a second NIC in the container. We then get a random ipv6 IP from networkd, and set it on this second interface, while also adding routing rules:
  - `301:...::/64 dev eth1` (the local node subnet on the second nic)
  - `200::/7 via ${yggdrasil_gw}` , where yggdrasil gw is the local yggdrasil ip in ndmz, as this is essentially the yggdrasil gateway on the node (this IP also needs to be provided by networkd).
- 0-db (containers) are already publicly accessible, so they should already be attached to br-pub. Meaning we would just need to set the IP and routes on the interface already present
- VM's already have support to set proper IP and routes if it is passed along in the network config. Since the public interface tap is attached to br-pub, this is sufficient and should work out of the box. However, the presence of a public interface right now depends on having reserved a public IP as well. We will need to modify the kubernetes reservation with a `yggdrasilIP bool` field, which governs setting the yggdrasil IP in the vm. If the field is present, and a public IP is not, we also need to set add a public interface tap with just the yggdrasil IP. Need to verify how to properly firewall this however

**Comment by LeeSmet** [comment]
As an alternative implementation which solves the firewall problem, we could create a new `br-ygg` in the host and connect all yggdrasil interfaces from containers and vms to this bridge. Then, we simply firwall the bridge to only allow the `200::/7` yggdrasil subnet. This bridge then is connected to the ndmz with a veth/macvlan, which essentially takes the local yggdrasil ip (instead of `npub6` as is the case now). This also nicely isolates the traffic of yggdrasil inside the node, as the bridge would not be connected to the outside world, only to the ndmz

**Comment by LeeSmet** [comment]
after some discussion, we will go for the approach with the host bridge
