### ISSUE TITLE
Disable ip on zos bridge

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/zos#1176]
Right now the zos bridge has an ipv4 (and ipv6) address. This is used for traffic from the host itself. After #1176 lands, zos will be the only bridge working like this. Disabling ip on zos as well would mean we have a single way of how bridges work (as a regular switch). For host traffic, we can create a macvlan (or veth pair if required) attached to the zos bridge on one end an on the host with the other end.

**Comment by muhamadazmy** [comment]
Can we make sure those changes are implemented on the new clean up branch instead of master?

**Comment by muhamadazmy** [comment]
Concerns:
- zos bridge is setup during boot by the `internet` service, not by `networkd`. so changes will apply only for new booted nodes
- if we also want to migrate current running nodes, networkd then have to check the current zos bridge setup, and create the new veth pair, and then connect them and rerun dhcp on the new pair. (hence a short host downtime)
- the new veth pair will have a new mac address (note that we already move the physical nic mac to zos bridge) so we will end up with a new IP (i am not sure if the 3 devices can/should have the same mac and if that would work) 
- complicate networkd boot to check and rewire zos for running node
- new booted nodes will still get different IPs (because of mac change)

**Comment by delandtj** [comment]
you can use the same mac address as zos, __if__ ipv6 is properly disabled __and__ the ipv4 addr is properly moved
