### ISSUE TITLE
the k8s worker node stuck

### ISSUE THREAD

**Issue by dmahmouali** [threefoldtech/zos#1238]
when I tried to ssh the k8s worker node, it's stuck and can't ssh.

worker reservation: https://explorer.devnet.grid.tf/api/v1/reservations/workloads/42992
node_id: 48YmkyvfoXnXqEojpJieMfFPnCv2enEuqEJcmhvkcdAk

**Comment by muhamadazmy** [comment]
CH version on devnet was missed up duo to their own build scripts which injected ZOS release version instead of CH version into their binary. so this made it impossible to validate which version of CH is running on this node.
I fixed that now, so now CH shows the correct version (this is now deployed to devnet only) so if this problem occurred again we can do a better debugging.

**Comment by dmahmouali** [comment]
the node works fine after the fix, Thanks @muhamadazmy

**Comment by AhmedHanafy725** [comment]
happened again 
**workloads:**
https://explorer.testnet.grid.tf/api/v1/reservations/workloads/35978
https://explorer.testnet.grid.tf/api/v1/reservations/workloads/35955

**Comment by muhamadazmy** [comment]
Both machines don't have logs, can u validate that the failure to reach the node is not related to wireguard not running or no wireguard handshakes ?

**Comment by AhmedHanafy725** [comment]
Now both workers are reachable through wireguard.

> Edit:
The nodes were never stuck, but wireguard for this network was down. Please next time make sure that wireguard is up and that the handshake is good (in case the access node was down)
