### ISSUE TITLE
Extract network manipulation logic from tnodb

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#124]
Currently most of the logic regarding network object manipulation lives inside the [tnodb_mock](https://github.com/threefoldtech/zosv2/tree/master/tools/tnodb_mock)

While this makes things super easy to use, it doesn't really fit with the concept where the node only provision what they get from the bcdb. Instead the node is now dynamically talking with the tnodb by itself and the [network object](https://github.com/threefoldtech/zosv2/blob/master/modules/network.go#L66) is modified without the owning user knowing it.

To solve this and move the full control to the user we need to let the user create the network object by himself (using the lib, manually this is way too complex)
Then the user can send the network object as a provisioning request to the bcdb.
The bcdb will only validate the content of the network object. If the network object is not correct the provisioning will be refused by the bcdb.
 
Tasks:
- [x] extract all the network object manipulation logic into a library (fb3d753ed2395fde8e19a336c662cbdcb8d68781)
- [x] remove some endpoint from the tnodb_mock (fb3d753ed2395fde8e19a336c662cbdcb8d68781)
  - [x] create network
  - [x] add member
  - [x] add user
- [ ] implement a full network object validation that will be used by the bcdb when provisining network: will be done in https://github.com/threefoldtech/zosv2/issues/132
- [x] update provisiond to support the a network object as provisioning request (aed0c23811a26a4d2e9993b4f3d9285765d3b2a0)
- [x] networkd should not watch the network object anymore, but just react upon provisiond request (watcher could be move to provisiond) (aed0c23811a26a4d2e9993b4f3d9285765d3b2a0)

**Comment by delandtj** [comment]
there a a few caveats to consider:
  - if HIDDEN nodes live on the same segment (or routable internal network) we should be able to specify that, so that the WG config can still address the inhouse peers like they do as being public. [shown here](https://github.com/threefoldtech/zosv2/blob/master/specs/network/HIDDEN-PUBLIC.png)

  - Dual-stack Nodes (IPv4 AND IPv6) need to verify if a peer is effectively reachable through either protocol, as there can be only one Endpoint be configured. [This doesn't exist in Wireguard yet](https://lists.zx2c4.com/pipermail/wireguard/2017-January/000917.html), now everything is a 1-1 key-IP mapping.
  - the lib __still__ needs to get an allocation from an Exit Prefix Provider (need to find a name other than 'Farmer' ?) that keeps track of the allocations of Network Resources, and thus also the routing for these Prefixes to the correct ExitPoint. So in the verification we should make sure there are no collisions.

**Comment by zaibon** [comment]
All the task have been merged in #131 except `implement a full network object validation that will be used by the bcdb when provisioning network`

I'll create an separate issue for it so I can keep this one closed: https://github.com/threefoldtech/zosv2/issues/132
