### ISSUE TITLE
Reflect on how billing for bandwidth and network allocation will work

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#128]

**Comment by muhamadazmy** [comment]
Some humble thoughts on how this should be done:
- Calculations should **ONLY** concern with actual outgoing/incoming traffic.
- Provisioning for network namespaces, bridges, wiregurard, etc... shouldn't be billed because on their own they cost nothing. Only traffic counts.
- Network metrics are collected per each *Network*  namespace (tx, rx) bytes, and packets per second.
  - problem is that this doesn't differentiate between `localhost`, `LAN`, or `WAN` traffic.
- The metrics of the network is published on zbus as an (event) other services can subscribe to this event to read traffic reports (and other types of metrics from other daemons as well). The reported information should have usage plus information about the network object that caused it (which can be linked to a tenant).
- Other services like the UI screen, or billing aggregator can subscribe to these events and plot them.

This raises 2 questions that I am not sure about their answers:
- How to differentiate the local, or internet traffic since they probably gonna be billed differently without doing netfilter conntrack statistics (not sure how expensive is this, and if we can have the correct rules to do this even... needs research)
- How the user is billed, since reservations are pre-paid how to pre-pay for a traffic that you didn't use yet. Should we bring the network down if the user exceeds his quota (like expiration for other resources)

**Comment by weynandkuijpers** [comment]
This is a growing concern amongst Farmers with the changed token economy.  In the previous token economy and simulator (google sheet) there was a line that included a "guestimate" of the network usage based on the number of CU and SU generated (and consumed in the end) of a farming node.  This represented an income line.

I the new simulator (jupyter notebook) this is no longer represented and therefore people are asking questions (in the forum).  Without influencing the delivery of this facility I would like to confirm the following:
- calculations will **ONLY** concern actual in and outgoing traffic to a node
- pricing for the traffic (NU's) are set by farmers.
- pre-billing is okay it at time of reservation a "package" is reserved (like SSD /HDD you reserve 10GB) here you reseve 10GB of ingress / egress.
- need to think about renewal of that package.

**Comment by zaibon** [comment]
> calculations will ONLY concern actual in and outgoing traffic to a node

Yes we want to track what goes in and out of the network resource interfaces. 

> pricing for the traffic (NU's) are set by farmers.

Eventually yes, like any other resources.

> pre-billing is okay it at time of reservation a "package" is reserved (like SSD /HDD you reserve 10GB) here you reserve 10GB of ingress / egress.

For this we need to reflect. Is bandwidth would be a new primitive that you can reserve for a specified network ?  This is more tricky since a network is used by all the other primitives and thus not linked with a single reservation. If we go for a pre-paid model, this means we need a way to cut connection when reserved bandwidth reserved is all used. I think this is both harder to implement and would be very strict on users. So I don't know.

**Comment by DylanVerstraete** [comment]
Closing because it's not relevant in 3.0 anymore.
