### ISSUE TITLE
IPC infrastructure

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#13]
We need to decide how API layer will discover and talk to all the low level modules.
Requirements:
- module needs to be discoverable
- module needs to be able to be upgraded without impacting the higher layer
- Capable of propagating events up the stack

**Comment by zaibon** [comment]
@muhamadazmy already did some research regarding dbus: https://github.com/threefoldtech/0-OS_research/blob/master/specs/ipc.md

**Comment by muhamadazmy** [comment]
# Proposed solution
- We use rabbitmq as a message bus
- A high level api wrapper that hides the implementation details of the message bus that exposes a clean integration api
- Each component then can implement it's API by exposing an object or more.

I will create a spec for the API, and link it here. Currently experiment with rabbitmq client

**Comment by maxux** [comment]
What about redis pub/sub ?

One discovery channel where module annonce themself, explaining which channels they will use.
And we can send messages/actions/whatever via theses channels.

We could also declare ourself a schema of what the module can do/want to do, and push it during discovery, and then get a centralized point of « what can I do with you ? »

You can always update modules separately, since communication channel are just channels sending/receiving arbitrary data.

**Comment by muhamadazmy** [comment]
Yeah, it's possible with redis, but rabbitmq has more sophisticated messaging platform. Even if we not going to use all the features, it's nice to have them in case we need them. For example, messages ack is nice in case one of the component has crashed while processing a message.

**Comment by muhamadazmy** [comment]
Anyway, the framework we going to build can/should be "messaging bus" agnostic. Implementation can be smart enough to support implementing different message brokers

**Comment by zaibon** [comment]
Zbus is the reference implementation for the message bus used in 0-os v2: https://github.com/threefoldtech/zbus/
