### ISSUE TITLE
Farming: Bios lockup to certify nodes

### ISSUE THREAD

**Issue by andhartl** [threefoldtech/zos#1319]
In order to provide certified nodes we need a mechanism to lockup the bios.This should be designed with scalability in mind as we are planing to sell thousands of boxes.

- [ ] scope 
- [ ] timeline

**Comment by sabrinasadik** [comment]
According to @LeeSmet, a simple bios lockup is not the way to go. When the farmer removes the battery, the bios resets & the lockup is gone. 
What's actually needed is a bios lockup + probably something like a TPM (Trusted Platform Module). This needs investigation, research & coding to be viable. 

@muhamadazmy can you take a look at this and give us your two cents, please?

**Comment by muhamadazmy** [comment]
My 2 cent is we check with  @maxux

**Comment by maxux** [comment]
For the old blockchain node, we added a security layer which prevent kernel to boot if secure boot was not enabled. But TPM is indeed something we would need to use aswell.

**Comment by sabrinasadik** [comment]
@maxux is this something you can put on your radar and work on? Need this as soon as possible, before the next batch of Titan nodes goes out.

**Comment by maxux** [comment]
Well, actually I think we face some problem.

Since we are fully open source (and even, that closed source would just make things difficult but not impossible), it's doable for anyone to build our stuff with custom modification. In that perspective, it will always be possible to a node to reply something which looks like presenting a certified node, even if it's not.

I think we should have a way to collect some unique information from the node and send them when node register itself. On registration process, we should check (in a central way ?) if theses information are registered as certified and not duplicated (used by two node in the same time). In this case, even by faking the system, except b stealing existing node identity, you cannot have a fake certified node running.

But thus, it's still difficult to ensure that the certified node is running a certified locked system, we can only ensure that node hardware is the expected node.

**Comment by LeeSmet** [comment]
So the idea I'm having is this:

Certification is a centralized process, so it makes sense that this is performed by TF when a node is sold, or someone related to TF (employee, licensed technician, ...) can make a node certified later. The node goes through the certification process and is then marked as certified by TF (how that works is out of scope here).

In practice we need 2 things: a locked bios with secure boot, and a TPM. These days, any half decent motherboard seemingly has  a TPM included. Though we might want to go with a stand alone hardware one instead. We should also consider if we want to support the older 1.2 TPM standard, or the newer 2.0. Personally I prefer the 2.0 one (there are known weaknesses in some models that use the older specs. Also, the latest spec ensure the new elliptic curve algorithms are available). This does mean that only UEFI is supported (not old style bios). In the end this should be fine since this is not something we want the farmer to do by himself anyway.

The setup would look roughly like this: 

First, the bios is locked and secure boot is enabled. Only the TF key used to sign kernels with is present. This ensures only a non modified zos image can boot.

Second, we have a TPM, which has certain configuration written to its registers as part of the certification process. We need to check what config, but at least PCR 7 should be set (secure boot state). We likely want to set others as well, though we should analyze there impact first. E.g. PCR 8 is a hash of the kernel cmd line, which might be useful to fix a certified node to a farmer, but could also impact the ability to boot some kind of debug image, if we ever make one.

Then, we can use a regular zos image. It should detect tpm availability and attempt to use it. Important here is that it *seals* all keys it uses/stores in the TPM. This ensures that these are only accessible if the register state is correct (so secure boot is active, bios has not been changed, ...), which together with the signed kernel ensures that only a signed zos can access the keys.

Important is that we offload cryptographic operations as much as possible to the TPM. In a perfect world, all encryption and signing is done through the TPM, so the (private) keys don't leave that device. If keys _are_ loaded to memory, this opens up the possibility of `a cold boot attack`.

Overal, we'd need to: 

- set up bios locking
- figure out how TPM works, in depth, learn how it works, what we can do with it, and what the benefits / disadvantages are. Also, we should consider v1.2 vs v2.0.
- Code interactions with the TPM in zos, and modify existing code paths to take advantage of it

Considering the current engineering focus, the (lack of) available resources, the projects that are being worked on, and the scope of this project / the implications it brings,  it is safe to say that this is not going to be delivered in the foreseeable future.

> before the next batch of Titan nodes goes out.

Not sure what the delivery date is, but I'm going to say that's a no.

**Comment by maxux** [comment]
That sound really great and meets my ideas !
I still have a concern, how can we ensure that a node booted and registered is effectively a certified node ?

Using the key we put on the TPM (and nowhere else), to sign something unique during registration and compare with a db (blockchain) which contains public key ? We need to ensure this key cannot be leaked then.

**Comment by LeeSmet** [comment]
> I still have a concern, how can we ensure that a node booted and registered is effectively a certified node ?

Afaik a tpm has the ability to sign data on chip. In this setup, a node identity key os created during first boot as part of the certification process. At this point, we know the HW, and we verify the data is acurate on the explorer, so no error occurred. We then have the public key. Since the data is signed on the tpm, the private key never leaves that and is secure (assuming the tpm itself is secure). This eliminates the option of a cold boot attack, not sure about a hardware attack on the tpm chip itself ofcourse

**Comment by maxux** [comment]
That sound really good. Let's get some hardware with TPM 2.0 to play with :p

**Comment by maxux** [comment]
Some update here. I could play with the fTPM in my laptop and get some RSA key installed that I can use to sign stuff.
I will explore more in deep how registers etc. works in order to get secure boot really secure, but all of this can be done remotely, we don't need any extra physical access to Certified Node now.
