### ISSUE TITLE
Deployment update order is divided into stages breaking workload order constrains 

### ISSUE THREAD

**Issue by OmarElawady** [threefoldtech/zos#1422]
The update procedure goes through this steps in order:
1. uninstall deleted workloads
2. update existing workloads
3. create newly added workloads

The workload deployment has some order constrains like the mounts being before the zmachines. But this doesn't hold in the following scenario:
1. Deploy a deployment container with no mounts
2. Update the deployment with a mount

The container is updated first before the mount is deployed.

**Comment by muhamadazmy** [comment]
It's not according to the code here https://github.com/threefoldtech/zos/blob/main/pkg/provision/engine.go#L532

are you sure this bug is originated from this?

**Comment by muhamadazmy** [comment]
I think the problem is that, the update is done before install, so a new disk will not be created yet. as in here https://github.com/threefoldtech/zos/blob/main/pkg/provision/engine.go#L402

A fix (imho) would be switching those 2 lines. so install comes before update. (which makes sense) but a decent testing should be done first.
