### ISSUE TITLE
zos3: qsfs update while mounted on a zmachine doesn't work

### ISSUE THREAD

**Issue by OmarElawady** [threefoldtech/zos#1430]
Steps to reproduce:
1. Deploy a qsfs and a vm with the qsfs mounted on it
2. Update the qsfs without updating the vm

`df -h` shows socket not connected error.

**Comment by muhamadazmy** [comment]
I think the problem here is that zos does not know how to update a running qsfs mount!
if a workload config has changed, and there no custom code path the tells it how to update, the provision engine will instead do a 'deprovision', then a new 'provision' with new config. This default might be the problem and may be it's better if zos can not update running workload that it returns an error instead.

Then what happens is that the entire qsfs is deleted and then recreated. Now how the virtiofsd is gonna react for the shared directory being gone. Does it exit? 

What needs to happen instead, implement an update method for the qsfs type, that basically re-rewite the config and restart the zstor process (alone)

**Comment by muhamadazmy** [comment]
Linked to https://github.com/threefoldtech/zos/pull/1432
