### ISSUE TITLE
failed to find IP address on zdb0 interface: failed to get an IP for interface: failed to get interface eth0: Link not found

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/zos#1453]
While deploying zdbs on node 5, got this error

env: devnet 
deployment's contract_id: 220

```
failed to find IP address on zdb0 interface: failed to get an IP for interface: failed to get interface eth0: Link not found
```

**Comment by muhamadazmy** [comment]
This issue happens because the interface name has changed from `zdb0` to `eth0` in newer zos code. the problem is that old ZDB instances that are already running, still has the old interface name `zdb0` but the code is looking for interface `eth0`

So
1) This issue should not happen anymore after devnet reset (that include wiping up the nodes)
2) I will add some backward compatibility code to check for zdb0 interface if eth0 not found.
