### ISSUE TITLE
wireguard user network is accessible through the public interface

### ISSUE THREAD

**Issue by OmarElawady** [threefoldtech/zos#1458]
Steps to reproduce:
1. Deploy a machine with specs:
- network: net1
- private ip: 10.0.1.2
- public ip: 185.206.122.46
2. Deploy a second machine:
- network: net2
- private ip: 10.2.1.2
- public ip: 185.206.122.47
3. On the first machine listen only on the private wg ip `nc -l 10.0.1.2 4000`
4. On the second machine execute `ip r add 10.0.0.0/16 via 185.206.122.46`
5. curling 10.0.1.2:4000 arrives to nc

**Comment by muhamadazmy** [comment]
I don't get the usage of the second machine in this case. what if u added the routing rule on you laptop, (while wg is down) can u still reach 10.0.1.2:4000 ? 

Can u check if first machine has ip_forward = 1 ? from your setup it seems it's the VM(1) problem that it's configured to work as a gateway, hence forward the traffic.

**Comment by OmarElawady** [comment]
I think the next hop must be on the same network subnet, so I can't add the public ip as the next hop from my local machine. `sysctl net.ipv4.ip_forward` is 0 on both machines.

**Comment by muhamadazmy** [comment]
TBH I don't think this is a "zos" issue, it's how the VM itself is configured to gateway traffic. any linux machine can work as a gateway between any 2 "connected" networks.

The traffic is routed (I assume) inside the VM context, not on the host because there is a separation between the bridge handling public traffic and the bridge that handles the user network traffic.

Can u confirm:
- ip_forward is disabled on machine 1 (the one that has both networks)
- show me also nft rules on machine 1

Also VM2 now can't actual communicate with other vms in net2, correct?
