### ISSUE TITLE
my deployed VM restarted and lost my data

### ISSUE THREAD

**Issue by mhost39** [threefoldtech/zos#1492]
i deployed a VM on 26 october on node 3
```
{
    version: 1
    state: Created
    contract_id: 19
    twin_id: 30
    contract_type: {
      NodeContract: {
        node_id: 3
        deployment_data: 
        deployment_hash: d6541ffdf6a363b1ee78105d1ebf1639
        public_ips: 1
        public_ips_list: [
          {
            ip: 185.206.122.133/24
            gateway: 185.206.122.1
            contract_id: 19
          }
        ]
      }
    }
  } 
```
and this VM restarted and i lost my data 
![image](https://user-images.githubusercontent.com/31102305/144239988-3ce92732-f1fe-4ff2-8573-525baea1284f.png)

**Comment by mhost39** [comment]
i used this VM to run Grid Monitoring on it (TF Grid Monitoring telegram chat) https://t.me/+GMRysn0QlD39rC8U
(https://github.com/threefoldtech/Grid_monitoring)

**Comment by muhamadazmy** [comment]
Few questions:
- How did you restart the VM (i assume a decommission, and then a new commission) ?
- Is there a disk attached to the vm?

I am asking this because the rootfs of the Vm is deleted once the VM is deleted. But if the there is a disk attached to your VM the disk is not deleted when the VM is deleted. Because the disk is a workload by itself, not part of the VM workload.

So to preserve the data across "reboots" the data must be written on a disk workload, not the VM root. then if the VM is dead, or deleted, the data will stay on the disk, and can be reattached to a new VM.
