### ISSUE TITLE
Node testnet3.0 stop updating

### ISSUE THREAD

**Issue by luisanadal** [threefoldtech/zos#1505]
we have another testnet3 node that is not updating, according to the information shown at the consoles 1 and 2 it looks like the node cannot connect to your servers to perform the update, the hard drives were wipe out, 5 days ago, it was updating fine and  1 or 2 days after it started failing, see screenshots, 
Node's information: 
  - Farm: GEC-StGallen1-testnet3 (10)
  - NodeID:  110
  - IP: 10.6.1.67

![Screenshot from 2021-12-10 19-43-49](https://user-images.githubusercontent.com/58570148/145793937-07e6b574-de59-4f5a-89ad-3224fb9fe950.png)
![Screenshot from 2021-12-10 19-43-26](https://user-images.githubusercontent.com/58570148/145793945-d075bfc4-d2b2-4111-b425-162ad0fa5678.png)
![Screenshot from 2021-12-13 11-18-41](https://user-images.githubusercontent.com/58570148/145794402-bf901b14-a79e-4773-8e7a-810a6fe1b4be.png)

**Comment by muhamadazmy** [comment]
There are 3 issues i can see in the screenshots: not all of them are actual issues:
- the error from `noded` this happens when the node loses connection to the grid, and when happens the nodes tries to connect again and it was able to reconnect. this is completely fine. This happens regularly when the node doesn't not receive any updates from the grid for a long time so it timesout.
- the error from yggdrasil, this is probably duo to issues with the yggdrasil network peers. We already have a fix to this to find better peers, this fix did not roll to testnet yet. I can roll it out today since it has been running on devnet for couple of days now. But again this error doesn't mean the node is not reachable, just some latency over the yggdrasil network. Anyway, fix will rollout soon to testnet.
- The last one is error from promtail. That is indeed an issue from our side, a planned reinstall of the logging services is already in place. this is about the node failing to push its logs. This does not actually affect the node operation.

**Comment by luisanadal** [comment]
Hello, 

thanks for your email, 

did you do something? suddenly it updated by itself,

but something weird is that the old nodeIDs associated with that server
(old nodeIDs created before we wiped out the Hard drives) are showing
in the explorer updated too, is that normal?

nodeId    | farmId | farm                        | twinId |
ips          | mac               | uptime   | updatedAt    | hostname |
cru | mru          | sru            | hru            | status
84        | 10     | GEC-StGallen1-testnet3      | 122    |
10.6.1.67    | 08:f1:ea:95:42:da | 9 days   | 1 hours ago  | N/A      |
64  | 270363607040 | 0              | 0              | ONLINE
110       | 10     | GEC-StGallen1-testnet3      | 182    |
10.6.1.67    | 08:f1:ea:95:42:da | 9 days   | 1 hours ago  | N/A      |
64  | 270363602944 | 7681533640704  | 96001109000192 | ONLINE
99        | 10     | GEC-StGallen1-testnet3      | 160    |
10.6.1.67    | 08:f1:ea:95:42:da | 10 days  | 1 hours ago  | N/A      |
64  | 270363607040 | 0              | 0              | ONLINE
103       | 10     | GEC-StGallen1-testnet3      | 165    |
10.6.1.67    | 08:f1:ea:95:42:da | 14 days  | 1 hours ago  | N/A      |
64  | 270363607040 | 0              | 0              | ONLINE

best regards

**Comment by muhamadazmy** [comment]
I don't get exactly what you mean. did u wipe the disks and now the nodes have new ids ?

**Comment by muhamadazmy** [comment]
Also i see the node 110 is shown as offline from the explorer. I tried to ping the node over yggdrasil interface but it didn't answer. Are u sure there is no firewall in the farm that is blocking yggdrasil traffic ?

**Comment by luisanadal** [comment]
i had wiped out the nodes time ago, let me explain,
all nodes but 110 are old, we were getting one nodeid every time the server was booting up, so we wiped all HDD and now is ok.
what I meant is that after the nodeid 110 started again being able to connect to threefold all other "old nodeids" were shown as updated too, which is strange, but no anymore, i just wanted to mention this :)

**Comment by luisanadal** [comment]
i have realized that the main screen is slightly different now we have some new information, showing "cache disk: ok", is it a new release?

**Comment by luisanadal** [comment]
i have other nodes with problems, 3 of them are showing a error with the cache: "LIMITED CACHE" and other 2 looks like are ok but no updates have happened for the last 2 or 3 days, 
do you want me to open a ticket for each
![Screenshot from 2021-12-17 11-54-00](https://user-images.githubusercontent.com/58570148/146534341-6719b4fc-97a1-4685-8c1a-8fa6a6f1a5c9.png)
?

**Comment by muhamadazmy** [comment]
Limited cash means the node doesn't have or not detecting SSD disks.
