### ISSUE TITLE
Abusing of the kernel ringbuffer for applications is frowned upon ;-)

### ISSUE THREAD

**Issue by delandtj** [threefoldtech/zos#152]
Although we can enlarge the kernel ringbuffer for these things, I woud refrain from using it as a log mechanism. 
the moment that the kernel is yelling about something, most probably our apps will also start spewing errors, and flush the messages that lie at the origin of all that babbling.

We need to discuss that.

**Comment by zaibon** [comment]
A dump as what as already been said on internal chat:

> Muhamad Azmy, [29.07.19 15:20]
these logs are not from zinit actually, they are just the services writing their output to the ring buffer

> Muhamad Azmy, [29.07.19 15:20]
not going through zinit

> Muhamad Azmy, [29.07.19 15:20]
but all outputs in general are buffered

> Jan De Landtsheer, [29.07.19 15:20]
speaking of which

> Muhamad Azmy, [29.07.19 15:20]
so logs can printed sometime before they are actually written

> Jan De Landtsheer, [29.07.19 15:20]
we shouldn't abuse of the kernel ringbuffer

> Muhamad Azmy, [29.07.19 15:21]
probably the start logs thingy are flushed once the service is stopped before it exits

> Muhamad Azmy, [29.07.19 15:21]
hence they appear after the stop is called

> Jan De Landtsheer, [29.07.19 15:22]
we actually need it to be as kernel-y as possible, because if something goes wrong in the kernel, we'll enever know, as because of problems reported by the kernel will immediately flushed away by failing stuff just because of the kernel problems

> Jan De Landtsheer, [29.07.19 15:23]
imagine a disk breaking, storaged flushing the kernel RB because of it's own problems, then we have no visibility any more

> Muhamad Azmy, [29.07.19 15:24]
in that case we will need to run our own log buffer

> Jan De Landtsheer, [29.07.19 15:24]
THIS!

> Jan De Landtsheer, [29.07.19 15:25]
https://github.com/andylokandy/arraydeque smt like this

> Jan De Landtsheer, [29.07.19 15:25]
love the smiley.. it's applicable 😃

> Muhamad Azmy, [29.07.19 15:29]
actually no, we need to expose a "device" on the system where process can open and write to same as we do with kmsg

> Muhamad Azmy, [29.07.19 15:29]
may be this can be used as a library to handle the actual buffer in memory

> Jan De Landtsheer, [29.07.19 15:30]
with this  ash while read line? I think it's ugly

> Muhamad Azmy, [29.07.19 15:31]
i would like to remove this, but this was just a hack to prefix the log line with the service name

> Muhamad Azmy, [29.07.19 15:31]
if we implement our log ring buffer, this can be prefixed by the log daemon itself

> Muhamad Azmy, [29.07.19 15:31]
depends on how we going to implement it

> Jan De Landtsheer, [29.07.19 15:32]
we'd better have stdout and stderr redirected to indeed some device (but separate) to have a distinction beteween errors and logging

> Muhamad Azmy, [29.07.19 15:32]
yeah, nice

> Muhamad Azmy, [29.07.19 15:32]
i will see if we can use buse in rust

> Jan De Landtsheer, [29.07.19 15:38]
not found 😉

> Muhamad Azmy, [29.07.19 15:38]
C bindings :D

> Muhamad Azmy, [29.07.19 15:39]
also pipes can be used

> Muhamad Azmy, [29.07.19 15:39]
will work nicely with tokyo

> Muhamad Azmy, [29.07.19 15:39]
a named pipe

> Jan De Landtsheer, [29.07.19 15:40]
aye

**Comment by delandtj** [comment]
Delantre... pfff

**Comment by muhamadazmy** [comment]
I started a POC to create our own user space ring buffer log daemon. The logs will still be available only in memory (size configurable). 

I am still not sure how the logs should be read from memory though. Kernel ringbuffer provides a device (kmsg) for this. It's not easy to implement this in user space without using fuse, but there is no tokio fuse implementation for rust atm.

Another idea is using `mmap` (no idea about the support of this in rust), or finally named pipes.

**Comment by zaibon** [comment]
custom ring buffer has been merged into zinit: https://github.com/threefoldtech/zinit/pull/13
