### ISSUE TITLE
successful but unreachable deployments due to using a specific Linux directory as a mount point.

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/zos#1535]
there are two issues regarding the disks mount points:
1- mounting a disk to some Linux standard directories like `/var` or `/usr` will result in a successful but **unreachable** deployment.

2- it is common that the user could need to mount a big disk on `/usr` as it could grow independently as he added new software or `/var` which is designed for storing files that might vary wildly in size.

I understand that one could symlink all or specific sub-directories under `/var` or `/usr` after deployment to the directory when the disk is actually mounted and have a similar result. but it would be more convinced for users to have the disk mounted to where they want out-of-the-box after deployment.

so can we do **change the mount logic to copy pre-existent files** before mounting if the mount point directory specified by the user exists, to handle point no 2 above?

if the above suggestion is not feasible or not approved for any reason, **probably we could harden the mount-point validation** to have something like validating against a black list of the Linux standard directories that could cause issues with the deployment like the one mentioned in point no 1.

**Comment by muhamadazmy** [comment]
The problem is when u mount a disk on this location `/var` or `/usr` you hide the files that are provided by the flist so the VM will still boot fully but then no apps will be able to start because of missing important libraries and binaries needed for the normal operation.

On the other hand we can't just prevent the user to use those known paths. Because we have no idea what he is trying to run inside his VM. what if his entire flist is one single static binary and he needs to actually mount a disk under `/var` to use it for some data? We can never tell.

Of course using those paths is a bad practice, but it's not "wrong" per se.

**Comment by muhamadazmy** [comment]
And no, we will not copy the files from the flist to the disk. this not how the mount work. You can right now mount a disk on top of your /usr and linux will not complain or give errors, it will not copy files, but later on you will not be able to start new apps because of missing files.

If the user want this level of control he can simply use a VM image instead of an container flist, Or may be set the mount point to an empty string `""` so the vm will not mount the disk, but then later your `init` can mount the disk, copy the files and then remount it under the needed location
