### ISSUE TITLE
Expect full disk image instead of btrfs filesystem for /disk.raw

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/zos#1622]
Currently if a zmachine is a VM, `/disk.raw` must exist in the Flist, and it is expected to be a btrfs filesystem. This means that the kernel for example can't be part of the disk and can thus not be upgraded. A regular disk image would allow a lot more compatibility with existing cloud images.

**Comment by muhamadazmy** [comment]
Actually (and also because of the reasons mentioned here https://github.com/threefoldtech/zos/issues/1623) I was thinking the "VM" image should only provide the disk image (no kernel) and we always use our own kernel we use in containers mode. This means no cloud-init is needed since all the scripts to setup kernel and mounts will be already there. 

I am sure i created an issue for this before will try to find it.

**Comment by LeeSmet** [comment]
The problem with that is that as a user, if I have a VM, I expect full control over everything, including the kernel and filesystem in use, which won't be possible in this setup. For a container that is fine, as there you just want "some environment to run this application". By forcing a kernel of our own, the user can't even upgrade or change the kernel, as it is external to the image. Hence the suggestion in #1623 to use a bootloader firmware by default (so whoever creates the flist does not have to do it himself). Likewise, btrfs is a result of the fact that we already use btrfs internally to manage storage in zos, which is an implementation detail and should not be leaked to the user imo.

**Comment by delandtj** [comment]
so, if I understand correctly: if I want to create an flist for a vm:
- we need to create a raw file, 
- create a btrfs on it, loopmount it, 
- populate it, 
- add it to an flist, 
- alongside with some .img that contains a kernel... a kernel and it's modules ? or how do I have to look at that ?


Then the vm gets started, that does:
  - loopmount the raw file and 
  - expose that btrfs mount 
    - with virtiofs ? 
    - Or is the raw file directly exposed to the VM that mounts the volume? 
    
  But even then... how is putting a raw file in an flist in any way something that seems like a good idea ?

**Comment by muhamadazmy** [comment]
@delandtj nope this is not correct. 

We have 2 modes for a (VM) one we call containere mode, and the other is called VM mode (this VM mode is not really documented and rough) 

## In container mode
The flist has the rootfs of your VM or container so your flist has files like
```
/lib
/bin
/sbin/
/etc/
...
```
And so on. All what you have to provide in your `init` or what we call `entrypoint` this entry point can either be a single staticly build file, or systemd it doesn't matter.

ZOS, will use a custom build kernel + initramfs that can start up your VM (setting networks, and doing any extra mounts for extra disks, and then switch root and fire up your `entrypoint`.

The rootfs flist can has your entire system if you want, the problem is that we always use our kernel so a user can't provide his own kernel and we do this because we know how to interpret and process command lline arguments passed to the kernel on boot to setup networking and other stuff.

## In VM mode
The user can provide his own kernel, initramfs and a disk.raw. Then we can just start those directly but it's hard to build such flist because the user then need to also include in his init process all the scripts to setup the networking and mounts. This is why this is still rough.

What @LeeSmet suggests is that we integrate cloud-init to do this since it's an industry standard. So I was experminting with this and I think we can use it in both container and vm modes as follows:

- ZOS always build a 2MB fat32 device with the proper config.
- This is labeled correctly and attached to the system 
- To avoid include cloud-init into our initramfs we can write a small tool to read the cloud-init config (they are yaml anyway) and apply those config and continue the boot normally.
- In VM mode the user will still build an flist with his rootfs **including** a `/boot` directory with kernel + <initramfs>. His system must also then include cloud-init and required config to start it on boot (for example if entrypoing is systemd, then he has to have cloud-init enabled) 
- ZOS if the kernel is provided in the flist we use that instead (has to asked by the user) otherwise use default
- Cloud init can then take care of setting up the VM on boot.

We don't support the option for disk.raw anymore because this is not efficient by any mean anyway

**Comment by muhamadazmy** [comment]
Hmm, actually there might be an issue in the VM mode because someone still need to mount the virtiofs rootfs before the kernel from the flist is used.

**Comment by muhamadazmy** [comment]
Maybe the user then can still provide a disk.raw image in his flist and we use `rust-hypervisor-firmware` to boot the kernel from the image which must contain the kernel and cloud-init
