### ISSUE TITLE
Nodes don't show network config for a long time - "wait for slaac to give ipv6"

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/zos#1665]
We have several reports of nodes either not populating or taking a very long time to populate their network config. The follow messages and errors are seen:

![image](https://user-images.githubusercontent.com/17682591/164576991-977b70df-b15a-4c27-a546-e926922dc5d1.png)

![image](https://user-images.githubusercontent.com/17682591/164577038-bfd46eba-5348-46dc-aee7-4a1cfb1c88ed.png)

**Comment by muhamadazmy** [comment]
Can you provide the following information:
- Network (production, testing, development)
- Node ID that has this issue
- This issue is kinda old, what is the current state of the node? Waiting for ipv6 slaac ip maximum wait is 2 minute. When u say it's waiting too long for Ip how much is how long, and does it eventually resolve ? or the node still stuck
-

**Comment by scottyeager** [comment]
These nodes were on mainnet. Seems issue is resolved since I'm not seeing any more reports lately. Based on my memory, some nodes were taking two hours or more to get network config. Will close for now and reopen if needed.
