### ISSUE TITLE
failed to open hypervisor /dev/kvm failed to create vm, no such file or directory

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/zos#1715]
![image](https://user-images.githubusercontent.com/64129/170851629-4be0bde7-12e5-412c-a924-6af7426311c1.png)

**Comment by LeeSmet** [comment]
Missing /dev/kvm would indicate that virtualization is not enabled in the bios. Nothing we can really do about that although zos can easily check if this file exists and return a "nice"error message which could be interpreted by clients.

On another node, we might want a "capabilities" endpoint in zos, where a client can query the available options for the node. Running a VM might be one of those. 

Alternatively, since VM is a big part of running workloads (almost all useable workloads require a VM unless you want a 0-db), we might want to stop zos from registering itself if VM's are not enabled in the bios

**Comment by xmonader** [comment]
can we have some sort of protection against this one please @muhamadazmy ?

**Comment by muhamadazmy** [comment]
We as @LeeSmet suggests, add a check on /dev/kvm to return a nicer error. I don't think stopping the node from registering is a good idea because the node can still provide `storage` via 0-db but then registering won't be fair because it will be rewarded for cpu and memory while not being usable at all because of lack of virtualization.

This need more discussion

**Comment by xmonader** [comment]
After discussion we agreed on stopping zos from registration

**Comment by ashraffouda** [comment]
https://github.com/threefoldtech/zos/pull/1719
