### ISSUE TITLE
Zos reports high CPU usage

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/zos#1717]
Farmer sees the following on the Zos console, indicating high CPU usage but no CRU reserved. Node's power draw as measured with power meter is normal for idle state and not indicating high load either.

![image](https://user-images.githubusercontent.com/17682591/171272806-5bcc06b5-0679-440a-acc6-61663705596c.png)

**Comment by muhamadazmy** [comment]
I can see high amount of MRU reserved. The only workload that can reserve MRU is VM and this always come with CRU reservation as well. 
So this bug is not about the HIGH cpu usage, but rather why the CRU reserved is not showing anydata.

Anyway, this UI needs revisiting and  some love it has been neglected for a long time because the proper view should always be the chain, this is here in case there are some more sever errors.

**Comment by muhamadazmy** [comment]
Okay, i realized a lot of improvement have been done already on the UI since this regarding stats. i will close this as fixed for now and can be reopen if this happens again
