### ISSUE TITLE
Look into possible bug which causes some nodes to have a violation of uptime 

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/zos#1754]
Example: see https://github.com/threefoldtech/tf_support/issues/337

Some nodes are showing a higher reported uptime than possible, which causes them not to receive any tokens for the minting. Is this an issue related to zos?

**Comment by muhamadazmy** [comment]
I checked the issue. and checked current code on mainnet. 
- We already have improvement on the uptime reports. (sending the same timestamp already was not possible) but the improved reporting will make sure that the node will always report an uptime.
-  The only possible situation where I think this can happen if there are 2 (noded) daemons are running on the node at the exact same time. That is also very very unlikely and even if, them trying to report the exact timestamp is really tiny, that is almost impossible.

There is nothing i can do from zos side atm.
also @LeeSmet is this issue reproducable ? do we still have issues related to uptime since the last update of mainnet (2 weeks ago)

**Comment by LeeSmet** [comment]
I don't recall any uptime violations for june. There were mutliple for may and april. I don't have any way to reproduce it, it is just what the minting observes

**Comment by scottyeager** [comment]
Issue is a duplicate of #1713, which I'll close in favor of the more recent discussion here. In that case, the same node created violations for April and May. The fact that it didn't happen in June for that node, or any others, is a good sign that this was resolved by the last update.
