### ISSUE TITLE
No ssd detected after new drive added

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/zos#1765]
Farmer in farmer's chat reported this sequence of events:

1. Booted node with an ssd installed fresh from the factory, running fine
2. Added another ssd fresh from the factory (same make/model)
3. Node now reports "no ssd found"
4. Wiped both disks and then both were detected, running fine again

Now it's weird that the first disk worked without wiping and the second didn't (but maybe second drive came with a partition or volume for some reason). However, I don't understand why Zos didn't continue to operate as it did when the only first disk was installed. I guess the disk addition could have changed the disk ordering, but shouldn't Zos still move on to the other disk, find its node id, and boot properly?

**Comment by muhamadazmy** [comment]
This is a weird issue because adding a second disk "shouldn't" make the node suddenly show "no ssd found" because the first disk is still there. if the 2nd disk was not detected you should see that the total size of SSD space was not changed.

Q: I am wondering how the SSD was attached to the node? was the node powered off? ZOS doesn't support hot plugging of extra disks (a full node power recycle is needed).

**Comment by scottyeager** [comment]
Yes, I didn't think this matched expected behavior, but I wasn't 100% sure. I'll go ahead and close this as a one off that was resolved by wiping the disk.
