### ISSUE TITLE
Clearing public config fails

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/zos#1767]
On mainnet, attempting to clear the public config from a node fails with the errors seen below.

![A14D25BA-8B9C-4370-B920-63D0AED7A19D](https://user-images.githubusercontent.com/17682591/178815605-01d1ddca-48c3-43f6-a0d4-7f76cff98b5d.png)

**Comment by muhamadazmy** [comment]
Actually clearing public config is not supported. The node can't revert having public config cleanly (at the moment). 

@delandtj do you think this is a valid use case that need to be handled?

**Comment by muhamadazmy** [comment]
The problem is the `public` setup on the node is not revertible on the fly without breaking user networks on the node (wireguard) so to support this we give the farmer an option to modify user setups. 

Anyway, the cleanist solution I can think of to is the node can "clean up" config state then reboot itself. This will force the node to have a "working" networking stack. But still affect user networks that was active before this change.

**Comment by delandtj** [comment]
The public config is solely there for giving networking to the private networks. A Farmer can opt out of that and use his public IP's just for VMs. He can also only add an IPv6 public config (you know, IPv6 first, IPv4 as an afterthought). 
Either way, it is advisable to have a few (not necessarily for all nodes in the farm ) IPv4 public addrs on nodes for the Private network mesh and the farmer will earn tokens for that traffic (which can be substantial).
So it's a choice at setup right now, and the necessity to reboot for removing them is not that big of a problem.

**Comment by delandtj** [comment]
Even more, once some WG connections are established, I would make sure we can't delete the public IP addrs any more, as it will break the networks.

**Comment by muhamadazmy** [comment]
> 

Yeah, that's the main problem at the moment. Even if we rebooted the node to cleanely rebuild the network. The user still think his network still uses this specific public IP.

The thing is we can't prevent the user from "unsetting" the public config on the chain. and it's gonna be impossible to report back a setup error to the farmer. unless he checks the zos screen maybe.

**Comment by muhamadazmy** [comment]
I was thinking if both `rebooting` and/or deleting the public namespace will break user networks anyway. And there is no way we can prevent the farmer from deleting the node public config on the chain then may be it's just better to delete the namespace. user networks will stop working in both cases. it's up to the user to reconfigure his deployments once this happens!

What do u think? @delandtj

**Comment by scottyeager** [comment]
Thanks for the discussion guys. Not supporting removing the public config without a reboot makes sense to me, but I saw the errors suggesting that Zos was attempting it.

It's definitely bad news if a farmer does this while workloads are using the gateway. With that in mind, it's probably best that a reboot is required, so the farmer has a chance to "undo" before any workloads are broken if they remove the config by mistake.

If we can retain the current behavior while replacing the console error with a message indicating reboot is required to apply changes, I'd say that's a nice solution.

**Comment by muhamadazmy** [comment]
@scottyeager the reboot is done automatically once the farmer unset the public config. The node clears the config and immediately take the reboot action. 

The node need to destroy the public config immediately once it's unset because it's not granted that the ip is reused by something else or another node then can cause even more harm. Hence after config is removed, the node immediately clean up and reboot.

The dashboard of the farm then need to confirm multiple times and give enough info about the consequences of removing or updating the public config.

**Comment by scottyeager** [comment]
Understood @muhamadazmy. I agree that preventing user error by farmers is better done in the front end. Have opened an issue on the dashboard repo with your recommendation.

**Comment by mohamedamer453** [comment]
Verified in https://github.com/threefoldtech/tfgrid_dashboard/issues/107 clearing a node public config is now possible and it's reflected in the grid_proxy after clearing the config and can be checked from there. however as seen in the dashboard issue there's only one confirmation message before signing the transaction and then clearing the config and it just mentions that your're about to delete the config and that this action is irreversible.
i'm not sure if this message is enough or not for a process like this or not so if it's not enough of a warning for the user please reopen the dashboard issues with more info about what kind of warning should be added.
