### ISSUE TITLE
Zlogs not working with planetary ip

### ISSUE THREAD

**Issue by mariobassem** [threefoldtech/zos#1768]
I tried to deploy a zlogs workload using a planetary ip, and it didn't stream any logs. I also tried the same configurations but with a public ip instead and the logs were streamed successfully.
I tried to investigate the issue and found that the yggdrasil service runs in ndmz network namespace, while the tailstream service runs in another network namespace (n-87jwedc3tytHS in my case) and this namespace had no yggdrasil connectivity.
Running the tailstream service in ndmz namespace solved the issue though.

**Comment by muhamadazmy** [comment]
We can't run tailstream inside ndmz. The reason we run tailstream inside the `user` network namespace is to be able to stream the logs to other user private VMs. Hence running inside ndmz is not possible, otherwise this feature will not work.

In the matter of fact, it was never claimed that using YGG ip is possible with tailstream. Tail stream can only stream logs to:
- real public ips (v4, or v6)
- other user private VMs.

check docs here.
https://github.com/threefoldtech/zos/tree/main/docs/manual/zlogs 

Why do you want stream to yggdrasil address ? if you wanna stream logs to local PC or laptop, just use the private `wg` ip address assigned to your IP in the same VM network
