### ISSUE TITLE
Grub install fails in Ubuntu 20.04 full VM

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/zos#1821]
I've deployed some full VMs from `tf-official-vms/ubuntu-20.04-lts.flist`. Then tried a full system update:

```
apt update
apt upgrade
```
It brings up a prompt:

![image](https://user-images.githubusercontent.com/17682591/198772546-0057ae6d-a6f6-49b8-bf65-c249127095c5.png)

I can continue with `Yes` and this doesn't seem to cause any problems. However, it does interrupt the operation of Ansible playbooks that attempt a full system update.

Relevant output from `apt`:

```
Setting up grub-efi-amd64-signed (1.173.2~20.04.1+2.04-1ubuntu47.4) ...
Trying to migrate /boot/efi into esp config
Installing grub to /boot/efi.
Installing for x86_64-efi platform.
grub-install: warning: Cannot set EFI variable Boot0000.
grub-install: warning: efivarfs_set_variable: writing to fd 7 failed: Invalid a
rgument.
grub-install: warning: efivarfs_set_variable: failed to unlink /sys/firmware/ef
i/efivars/Boot0000-8be4df61-93ca-11d2-aa0d-00e098032b8c: Invalid argument.
grub-install: warning: _efi_set_variable_mode: ops->set_variable() failed: Inva
lid argument.
grub-install: error: failed to register the EFI boot entry: Invalid argument.
Installing grub to /boot/efi.
Installing for x86_64-efi platform.
grub-install: warning: Cannot read EFI Boot* variables.
grub-install: warning: efivarfs_get_variable: read failed: Invalid argument.
grub-install: warning: efi_get_variable: ops->get_variable failed: Invalid argu
ment.
grub-install: error: failed to register the EFI boot entry: Invalid argument.
```

**Comment by muhamadazmy** [comment]
Here is what I think is going on:
- in zos to boot a vm from an image we use a hypervisor firmware instead of a linux kernel. this firmaware basically acts as a bios and loads the real kernel from the image
- The firmware we are using has a minimum implementation of UEFI only enough to support the booting. But does not implement the full specs. 
- While the system boots from efi, something like efivars does not work which causes group-install to "think" if failed! 
- If you selected yes, the installation will continue.
- While there is a warning that the machine can get broken, i tested it and it boots just fine (if it crashed, or if you just power it off) it comes back normally.

Possible solution:
1- Document this issue, make sure that users know about this issue and that it's safe to ignore the issue.
2- Find a replacement firmware that implements the full EFI specs. Although I still prefer to keep the one we are using right now because it's maintained by cloud-hypervisor itself so we know it's always compatible. and tested with all official images.

May be close this issue as won't fix?

**Comment by xmonader** [comment]
Let's have it documented as a known issue and close it as a won't fix

**Comment by despiegk** [comment]
it cannot be closed because you cannot script with it,

```bash
sudo apt update -y
export DEBIAN_FRONTEND=noninteractive
sudo -E apt-get -o Dpkg::Options::="--force-confold" -o Dpkg::Options::="--force-confdef" upgrade -q -y --allow-downgrades --allow-remove-essential --allow-change-held-packages
```

this need to be put in forum and manual, because otherwise people will get stuck

**Comment by despiegk** [comment]
<img width="571" alt="image" src="https://user-images.githubusercontent.com/6021844/206898101-68508187-7abb-4e3b-8181-3f7c81349d6e.png">

**Comment by despiegk** [comment]
I made scripts to work around it see above, but then when I install something else keeps on complaining
can't automatically do yes

**Comment by despiegk** [comment]
<img width="1231" alt="image" src="https://user-images.githubusercontent.com/6021844/206898195-39328516-93f9-476f-ad8b-78e877a16743.png">
very annoying because every simple install afterwards keeps on failing

**Comment by despiegk** [comment]
i found a work around
apt-mark hold grub-efi-amd64-signed

is holding the package back from being installed

when we deploy machines we should uatomatically upgrade and do this

**Comment by weynandkuijpers** [comment]
How do we publish this as a temporary workaround (if it's temporary)...

**Comment by mik-tf** [comment]
I made a QnA out of this and will put it in the user/deployment section of the FAQ in the following days.

I'll write it here in case people want to modify and propose changes to the QnA:

***

### When deploying a virtual machine (VM) on the Threefold Grid, I get the following message after trying a full system update and upgrade: GRUB failed to install to the following devices... Is there a fix to this issue?

If, when deploying a virtual machine and doing a full system update and upgrade:

> apt update
> 
> apt upgrade

you get the error: GRUB failed to install to the following devices /dev/vda15, try this to fix it:

> apt-mark hold grub-efi-amd64-signed

This should fix the issue.

**Comment by xmonader** [comment]
@Mik-TF thanks!
