### ISSUE TITLE
Unknown error on test net node 

### ISSUE THREAD

**Issue by Parkers145** [threefoldtech/zos#1822]
![CD44422E-93EA-4906-B431-3D391E0CB0DB](https://user-images.githubusercontent.com/44621168/198842015-01e3ed34-b9f9-4317-8031-cd6ca59572d7.jpeg)

Node 219 on test net

**Comment by muhamadazmy** [comment]
Does this happen during installing a deployment ? This error does not make any sense because this log message should never come out from the `noded` daemon! 

Can you explain to me the circumstances around this error? did it just appear out of no where ? where you deploying a workload? and if yes how did you deploy it?

In general this means whatever is signing the deployment is not using the correct key

**Comment by Parkers145** [comment]
I was actually just hanging out in the office and noticed it started doing this, but I believe based on the time stamp of the post, this would of been when @scott testing on my farm.
