### ISSUE TITLE
Scaling up VMs and disks

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/zos#1824]
Currently, deployments have a static amount of capacity until they are destroyed. Some cloud providers offer the ability to scale up (but usually not down) the cpu and memory allocated to a VM, as well as the size of disks. In response to a query from the community, I'm opening this issue to track the feasibility and level of interest for adding this feature to the grid.

Many use cases for scaling a VM or disk in place can be addressed by giving deployers more flexibility in how disks and VMs are related. Namely, attaching a larger disk to an existing VM or transferring a disk to a different VM.

Some scenarios, however, would still benefit from scaling, aside from just continuity considerations. For example, if a VM is already reserving half of a node's available SSD capacity, it cannot simply reserve a new disk with the full capacity and copy its data to the new disk. The ideal solution, instead, would be to scale up the size of the disk.

**Comment by muhamadazmy** [comment]
- Moving disks from one machine o another is already supported. ZOS nodes supports update deployments operations. This can go like this:
  - You create a Disk, and a VM (vm1) and attach the disk to the vm.
  - After some time, you can simply drop the vm (make an update and remove the vm from the deployment)
  - This does not affect the disk, the disk remains
  - Create a new VM with different specs (different ram or cpu) and add the disk back to it
  - When the machine boots it will have the disk
- Also disk resize is supported as well, the only missing part is that changing the disk size while the disk is attached to the VM has no effect. this part needs some care and testing because it wasn't a required feature. I can look into this.

**Comment by muhamadazmy** [comment]
I tested the disk resize operation and here are the list of limitations that has to be taking into account:
- You can only resize a disk if it's not attached to a VM 
- You can only increase the size of a disk, you can't shrink it.

The operation goes as follows (also explained above)
- Delete the VM. deleting a VM does not delete attached disks 
- Resize the disk 
- Create a new VM on the same disk. 
- VM can now use the full new disk.

> Note: when using cloud-init images, once the node is booted with a disk the machine will resize the filesystem to allocate the full disk. If the resized disk is a data disk the user has to do this himself.

resizing the disk of course does not wipe the data.

There was a little bug in code that prevent the disk state to be reported correctly which i fixed on devnet. should make it to next release

**Comment by scottyeager** [comment]
Thanks @muhamadazmy.

**Comment by RobertL71** [comment]
Managed to increase a disk, or rather mount by using lvm. I started a vm with 50 gb through terraform. The deleted the vm leaving the disk intact, added another disk and redeploy.
Using lvm managed to add the new 100 gb to the already existing 50 gb volume, making 150 (148)

Is this what you mean?
