### ISSUE TITLE
Less SSD capacity measured for same HW 

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/zos#1827]
User reports to have received 726.6TFT less for both of his nodes. They were both online 100% of the time last month as well as this month. Looks like there has been 1TB of SSD capacity measured less than previous month while the HW specs did not change. A couple moments later another user reported to have received 10% less tokens as well, so might be an overall zos problem? 

Node 4401:

Last month
- CU: 59.617
- SU: 12.389
This month:
- CU: 37.26
- SU: 7.92 

Node 4337:

Last month:
- CU: 59.617
- SU: 12.855

This month:
- CU: 37.26
- SU: 8.38

**Comment by LeeSmet** [comment]
Also, both nodes reported above had 100% uptime last month (so no reboot). Minting considers the lowest amount of resources during the period. These 2 items combined means the only time this issue could occur is during a mainnet release.

**Comment by muhamadazmy** [comment]
@LeeSmet I don't get what you mean ? also I am not sure why this is considered a ZOS issue if the total amount or resources reported to the chain did not change? for example resources for node 4401 as shown here https://gridproxy.grid.tf/nodes/4401 shows it has 2TB SSD same for node 4337.

**Comment by LeeSmet** [comment]
To clarify, the reduction in resources comes from ZOS updating the resoures on the node (both reported about 3TB SSD then changed to around 1.9TB SSD). Now, there was no reboot of these nodes last month, and updating the capacity on the nodes only seems to happen when noded starts. So to my understanding that means it happened when noded was restarted after an update of zos (not sure if that is related to the actual issue).

**Comment by muhamadazmy** [comment]
We investigated the node(s) and both of them has hard word problems. the 2 nodes has low level disk errors and the disks are just vanished from the system.
![image](https://user-images.githubusercontent.com/10920323/200552448-b092f11f-da93-4520-b353-575cd575e469.png)

the kernel is reporting some hardware errors. Since i don't have physical access to the node I can not be sure if the disks has been unplugged from the system or if they just failed 
![image](https://user-images.githubusercontent.com/10920323/200552835-23daf68f-1ccd-4451-b97a-5443d55cb456.png)

If the farmer is sure the disk haven't been unplugged from the system he can try to reboot the node see if they will show up again.
