### ISSUE TITLE
Paused workloads didn't go back running after funding the wallet

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/zos#1852]
### Environment

network: devnet
contract id: 13842
node id: 13

### Problem

the contract that carries this deployment went into a grace period and the workloads of this deployment got paused. then the wallet was funded with some TFTs and the contract became in the `created` state, but the workloads are still paused after a day of funding the wallet.

**Comment by muhamadazmy** [comment]
Event was raised in block `3310268`. But was not processed by the node. There are 2 issues here:
- Node need to sync with chain for paused/resumed contracts same way for cancelled contracts. Even if events were missed the node should be eventually consistent.
- Improve the events delivery. Already some work has been done on this so all events are granted to be received by the node. But events are published internally again for the designated service to process. This internal delivery need to be improved since it uses a PUBSUB mechanism a service can miss the event if the service is down by the time of publish.
