### ISSUE TITLE
node capacity is not reported correctly

### ISSUE THREAD

**Issue by mariobassem** [threefoldtech/zos#1857]
my local node only has 100 GB of SSD reserved, but it shows on the chain that it has 1 TB of hru, and 1 TB of sru.
this is a screenshot of the machine specs:
![Screenshot from 2022-11-27 15-48-12](https://user-images.githubusercontent.com/26723944/204138693-b54e8fe3-569a-4365-8215-58d5275d5f4f.png)

**Comment by muhamadazmy** [comment]
The screen 100Gb reserved ssd is the capacity reserved from entire node disks for the system (cache). This screen does not show the full node capacity.

For why the machines shows it has 1TB ssd and 1TB HDD is because the for development we use something called sparse files for virtual disks. Basically we create a file that is say it's size is 500G on disk but in reality is 0 on size (does not take any actual space on physical disk.

So we create 5 files of those types (500G each) and attach them to the vm. the vm sees it has 5 disks each of 500G. but in reality (the virtual disks) on your laptop will only use space when needed (when data is actually written to them.

This is no issue.
