### ISSUE TITLE
More flexible public IP assignment

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/zos#1859]
Some of our grid users have requested the ability to reserve more than one public IP attached to a single VM. Meanwhile, I have noticed that we're missing the ability to support the Kubernetes deployment pattern where load balancers are assigned from a block of floating public IPs (such as how MetalLB operates), which also provides some nice failover capabilities in general too. Finally, only a small subset of farms currently have working reservable public IPs, and it would be rather convenient if public IPs could be assigned to workloads on nodes running in different farms.

So, considering the above concerns, I am wondering about the technical feasibility and difficulty of three features as described below:

1. Assign multiple public IPs to one VM
2. Allow users to reserve floating public IPs, which can be claimed by VMs running in the same private overlay network *and* in the same farm
3. Support connecting either fixed or floating public IPs to nodes in different farms, something like how gateway nodes currently operate for domain based gateways

**Comment by muhamadazmy** [comment]
- In theory there is no limit of number of IPs a VM can has, but right now the workload allows only one public IP. I personally don't see the benefit of having multiple public IPs assigned to a single VM. since the the traffic will be still limited with the speed of the node data nic. Either we have each IP attached to a virtual nic in the VM or if all IPs are just assigned to the same virtual nic.
- for ZOS each VM, disk, network, etc.. is standalone. ZOS can't know the higher level setup built by the user or by operation tools like terraform. In other words, zos is not aware of how your overlay private network is layed out, what other VMs, or nodes are part of this network. This means that your setup and how nodes are connected is completely up to you and your terraform scripts, hence managing somethingn like floating public IPs is currently not possible (and probably not in the foreseen feature )
- Well, it's actually possible to use a public ip from a different farm. since this was asked by others as well. and it's supported via an flist. so it runs like an app on the grid. The idea is you can deploy an flist (VM + public ip) on the farm with the free public ips. This VM need of course to be part of your overlay network. The farm accept a single env var `TARGET` and the vm then will forward all traffic from it's public IP to the TARGET IP. the target IP then can be a private ip to any of the other VMs in your overlay network even outside that farm or even to your laptop.
I only recently asked terraform team to add an example for this flist on how to use @xmonader

**Comment by muhamadazmy** [comment]
The forwarder flist does not require much memory or storage so a 250M memory + 10M rootfs is more than enough for it to operate, so the usage of an IP from external farm comes with a little bit extra cost.

**Comment by Parkers145** [comment]
> The forwarder flist does not require much memory or storage so a 250M memory + 10M rootfs is more than enough for it to operate, so the usage of an IP from external farm comes with a little bit extra cost.

can 2 forwarders be pointed to the same back-end server?

**Comment by scottyeager** [comment]
Thanks @muhamadazmy. I think the forwarder is sufficient to meet the immediate requests we have, which I think are basically around some architectures that assume there will be two public IPs pointed at the same VM for whatever reason.

I'm fine with shelving floating IPs for now, knowing that they don't fit into the existing architecture. This seems like a very nice feature to have someday though, especially if we have more users expecting advanced features available on other clouds.

> can 2 forwarders be pointed to the same back-end server?

Don't see why not. I imagine the forwarder workload is just a container with a few `iptables` rules added.

**Comment by muhamadazmy** [comment]
For documentation purposes: the forwarder flist is here https://hub.grid.tf/azmy.3bot/forwarder.flist
