### ISSUE TITLE
Directly accessing HDD's on dedicated node

### ISSUE THREAD

**Issue by Nelson361** [threefoldtech/zos#1870]
QSFS is great, but only allowing that is limiting for common use cases. Allowing normal direct access to HDDs on reserved dedicated nodes will allow for easier sales. There is a significant demand for dedicated servers with 100+ TD HDD, but not with mandatory IPFS.

**Comment by Nelson361** [comment]
The 0GB increase in reserved HDD space over the entire year is proof of this.

**Comment by muhamadazmy** [comment]
Interesting suggestion. Support to access raw storage on HDD can be implemented, but since nobody is in control of the nodes/farms since they are all maintained by 3rd party farmers/datacenters, you can end up losing your data say if someone decide to take the node offline. 

Qsfs is trying to fix this issue by making sure the data is split and distributed on multiple nodes so that losing a percentage of the nodes won't cause data loss.

This issue should become a discussion or a forum post. feel free to use https://forum.threefold.io/
