### ISSUE TITLE
use official flists in zos

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/zos#1876]
I can see these flists used in the zos source code without being promoted 
- [x] https://hub.grid.tf/omar0.3bot/traefik.flist
- [x] https://hub.grid.tf/omar0.3bot/qsfs-v0.0.1.flist
- [x] https://hub.grid.tf/azmy.3bot/cloud-container-20221122.flist

**Comment by muhamadazmy** [comment]
True, i have been thinking about moving them to the official zos flists. The problem is they don't fit any of the official repos:
- They are not binaries that are auto installed with boot
- They are not apps that users can run themselves
- They are not a zos release flist!

They are mainly files that are needed (in certain cases) in the runtime. May be we can have them under `tf-autobuilder` if we can automate their building ? may be from a different repo
