### ISSUE TITLE
Some nodes have a lot of clock skew

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/zos#1914]
After mainnet was updated and metric reporting over vector was enabled, we noticed some errors when sending metrics to prometheus. After debugging it turns out that the timestamp on the metrics (set by the vector running on zos before sending the metrics upstream) was too far in the past. Some further debugging allowed us to identify offending nodes. Checking logs of one of these nodes, we see that recently ntpd fails quite a bit, and when it does succeed, it gets an error for being too far out of sync from the remote.

After some discussion with @delandtj, we think it's best to include the full `ntpd`, instead of the current stripped down version inside busybox, and also `ntpdate`. Then, `ntpdate` can be run initially to set the correct time, and we have a proper `ntpd` service with all features

**Comment by muhamadazmy** [comment]
Another (naive) proposal:
Since ntpd is part of the base image (busybox) and updating that won't fix affected nodes unless they reboot (to get the latest image) may be we can instead fix it as follows:
- Push a small utility script that gets and set the node date to some date from the chain (timestamp module)
- This won't be as accurate as nptd of course, BUT it will bring the time on the node close enough for ntpd to actually fix the time.

What do u think ?

**Comment by muhamadazmy** [comment]
the script can only update the date on the node if the skew is bigger than a certain value so this doesn't happen if not needed, then ntpd can then just take over once the skew is small enough

this mean we don't need to change the base image, the fix will work without a reboot as well

**Comment by LeeSmet** [comment]
Good for me as long as ntpd can bridge the gap between the time that is set and the actual time (which might be more than 6 seconds if a block creator is down)

**Comment by LeeSmet** [comment]
Ntp is running on the nodes, and on initial start it does a sync of time regardless of delay. Checking an actual graph of the evolution of the delay of the nodes based on metric time shows this:

![image](https://user-images.githubusercontent.com/22023708/223077842-a906d75d-6841-478d-87e2-fc9d778eee2f.png)

(note that this is an isolation of farm 218 on mainnet, this constitutes 4/5 nodes which are lagging at the time of writing. The other one shows a similar pattern)

All nodes are running for slightly over 6 months at the time the screenshot was taken. Since the graph is linear, we can use linear interpolation to determine when the skew started. In all cases this is well after the boot. 

This means the node effectively "started" lagging at some point. The current theory is that the node actually has a slightly skewed clock, and ntp managed to keep it in sync until the delay at some point got slightly too high, at which point it refused to correct it and this behavior appeared.

There are now 2 questions:

1. What causes this behavior?
2. How do we handle these nodes. The nodes are inherently broken, and the issue has been demonstrated to get worse as time passes (we could measure exactly how much delay increase there is, but eyeballing it leads to slightly over an hour of additional delay in a week)

**Comment by xmonader** [comment]
I moved this to 3.10 for investigation

**Comment by muhamadazmy** [comment]
The problem goes like this:
- when the ntpd starts it sets the node clock correctly (regardless how far the skew is) 
- ntpd make sure the clock is synched all the time, so tiny clock skews are corrected constantly as long as the service running.
- it looks like the clock is kept in check until suddenly the skew is too big that ntpd decides not to fix it anymore, we couldn't figure out what causes the skew to grow suddenly this big and then ntpd stops synching.

I can guess only one problem, is that the node clock (hardware) itself is corrupt! while rare but is possible, Another possibility i found online is this 

>One of your comments says you are running on a vhost. In this case, you are probably not going to have much success because your vhost's sense of time is going to be dependent both on the real host it is running on and by how busy overall the vhost is.

> Depending on the virtualization used, the vhost may not get a steady share of interrupts in a given time period. This will make the clock run faster, or slower, than is really happening. Since ntp is trying to measure changes on the assumption that your clock is a fixed-rate faster or slower than the rest of the world, this speeding up and slowing down will give ntp fits and it will probably eventually just give up, with the result that ntp -np shows time servers that ntp has deemed unsuitable.

> Your best bet if this is the case is probably a brute-force rdate -s $server every so often (like every six hours) to yank the clock around by its nose so that it doesn't drift excessively out of sync. But fine-grained accuracy is probably out of reach.


The reason we can't solve it "cleanly" is that in both scenarios above there is nothing we can do about it. (Except may be to periodically kill `ntpd` (say everyday) to make sure it force resync the clock but I really dont' want to do this because it's a very dirty solution plus it is not needed for the majority of the nodes that actually run correct clocks

**Comment by xmonader** [comment]
ntpd is forced is part of k3s image right now and few images as well, but indeed if it's relevant to the node's hardware, there's not much we can do about it.

**Comment by muhamadazmy** [comment]
what do u mean forced? you mean started on boot ? or actually restarted every specific period

**Comment by muhamadazmy** [comment]
There is no correct solution for this on zos. if zos is too big that ntpd can't correct it then there is something fundamentally wrong on this node (bad or fake hardware). Any hacks to correct this on zos is:
- Not worth it, since only really few numbers of nodes that has this
- Will probably hide an actual issue in the node
