### ISSUE TITLE
[mainnet] random kills of provisiond with `SIGBUS` 

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/zos#1922]
Known nodes to have the issue:
```
5GC8wty48uw6eCHrN4rqHym29nXJBXFxadWvgaVFDBtBVUfE
5HWUzjJW83ivyMXEUhWfLaPczzJFFJkrhuPo9WmpESHLGtxX
5DYoV1veSopgG9122E81orMRwSJ8JF4YZqKRdqzNtzC8qpSD
5EoheyGaWEvqH8on4hw8i6DUTMpvFkUJjRAPnn7oXqDpW2V5
5Gx5gk2uJobTRnGKiwxDMDLPpfsDmEeKF8PgZekc7ScKPA7Z
```

![image](https://user-images.githubusercontent.com/10920323/224125216-e6538b60-b342-48f3-a9b1-42d29f0392ef.png)

**Comment by muhamadazmy** [comment]
SIGBUS means program is trying to access invalid memory.  

![image](https://user-images.githubusercontent.com/10920323/224126112-315c3a00-1557-4c45-9686-c3f6a940bf12.png)

It's seen in this screenshot the boltdb is using mmap! that can be the cause of the invalid memory that triggers SIGBUS.

May be run db integrity check in a separate process that if faile, force reset the database?

**Comment by muhamadazmy** [comment]
it happens on opening the metrics rrd database. This we can safely discard if necessary. so as a fix provisiond can run some integrity check before it starts it's normal operation, and then discard the db if test failed.

**Comment by mohamedamer453** [comment]
Verified.

The mentioned integrity check was added in #1923, i'll close this issue since the mentioned check was added and since i don't have access to the logs from the mentioned node. but if there is a way for me to verify that this issue is not present anymore, please reopen the issue and let me know where to verify it from.
