### ISSUE TITLE
Improving Uptime reporting

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/zos#1941]
With the current uptime reporting implementation we can't calculate node uptime accurately. when a reboot happens, the time between the last uptime event sent and the node reboot can't be tracked (you can't tell if the node was up or down looking at the reports alone) and that period will be considered down. e.g. a node that reports its uptime every hour, if rebooted after 50 minutes from sending the last uptime event, it will be considered down for 50 minutes + boot time vs only a few minutes the boot takes.

Would it make sense to persist the uptime, and reset with every uptime event dispatch, to survive rebooting?

**Comment by muhamadazmy** [comment]
Hi @sameh-farouk . I do get the issue but here is the deal.
- First of all zos reports uptime every 40 min (that doesn't make much difference but it's a fact)
- ZOS if shutdown using the farmer bot (mainly part of power management) it makes sure to send one last uptime report before it shutsdown.
- If the node reboots unplanned, then (depends on the reboot time) the node loses max of 40 min of up time but that's not an issue because node uptime need to be penalized! right? It's not okay to reboot the node for no reason
- There is a suggestion to also create a maintenance mode where the farmer can mark his node as under maintenance, the node then can be turned off for a short while with no effect on uptime.

> I don't get your suggestion, please elaborate more ?

I also want to include @LeeSmet in this issue if he has any comment on that

**Comment by sameh-farouk** [comment]
> I don't get your suggestion, please elaborate more.

What I suggest is storing and updating (increment it every minute or so) the uptime in persisting storage and only resetting it (flip it to zero again) with every uptime event sent. so it can read like node uptime since the previous uptime event instead of the node uptime since the last reboot. and now we can calculate the exact uptime. e.g. if the node rebooted without sending an uptime event, as long as the node is down the uptime won't be incremented, but as soon as it boots again it will pick the last uptime stored and start to increment it till the next uptime event.

For the penalized part you mentioned, currently, it can't be predicted and we have no control over it.. it is up to when the node was rebooted and can be a few minutes and up to 40, right? So two nodes with same (actual) down time can be penalized differently as they would have different (calculated) down time. but with the suggestion I mentioned, we can detect the exact downtime and then we can penalize it based on the last downtime (from last uptime report) or maybe on previous reports too.

**Comment by xmonader** [comment]
@LeeSmet please check

**Comment by muhamadazmy** [comment]
I think we will keep the current model it works well with minting. 

If a node crashed immediately after an uptime report, then when it boots it immediately sends an uptime. A simple calculation (a report has a timestamp of the report and the uptime) we can know how long the node was down. 

- if report was after less than 40 min of the last uptime (node was rebooted immediately) then node loses no uptime then node loses only the difference between the 2 reports
- if report was after more than 40 min, then node in worst case loses max or 40 min (extra) which does not affect the total uptime percentage of the node if it does not happen that often.


I say we don't need to fix, the added accuracy does is not justified and already minting is taking all this into account
