### ISSUE TITLE
The IP address 185.10.157.198 is unreachable after rebooting node id 5469.

### ISSUE THREAD

**Issue by shng4you** [threefoldtech/zos#1962]
The farmer can deploy a HestiaCP on node 5469 a few days ago, and it worked fine, and he was able to ssh into it and set it up through the browser via 185.10.157.198:8083.  However, after rebooting node 5469, the IP address 185.10.157.198 is unreachable. But it shows up in the playground. Also, he can deploy another VM.
![image](https://user-images.githubusercontent.com/95933607/236218794-92307f3f-0ded-47b4-b5c1-8caae36473b1.png)

**Comment by muhamadazmy** [comment]
Hey
I finally managed to dig out what went wrong with this VM. during the node booting, it did try to restore the VM but then failed to do so with this error `"could not look up ipv6 prefix: no public ipv6 found"` which basically means the VM required IPv6 but the router was too slow giving IPv6.

This can only means router didn't do router advertisment in time, at least during the node booting but later it worked hence creating new workloads (with public ipv6) will work fine.

Unfortunately the VM now is an unrecoverable state (well at least not without a lot of work from the user side, and what tools he used to create the deployment) 

I suggest the user/farmer can cancel this contract, and start over for now! I will look more into if this error can be avoided in the future.

**Comment by shng4you** [comment]
Thanks, Azmy, for the update and finding the solution. I will follow up with the user and what tools he used to create the deployment.

**Comment by shng4you** [comment]
First, I used Terraform; should I be able to destroy it? That IPv6 issue sounds like something that was seen before, assuming it is the same problem. Initially, we had quite some problems setting up all the nodes and networks in this data center. Jan helped us enormously. One thing they did is to ship us an openwrt that was pre-setup. Well almost. Still, the problems weren't resolved. Eventually, Jan reported a slow advertisement of the DC router. I don't know which IP type this was. He changed something on the OS side of things to cope with the slow advertisement. That worked. Does this mean this problem was reintroduced? It would be good to verify with Jan. Then last, the scariest part is that I was going to run this node as a Shared web hosting server. Imagine if I had a couple of dozen websites running, and this happened. Imagine the claim I'd get. What assurance do I have this won't happen again?
I'd feel much more comfortable if we would test the crap out of this; I'd even take time to sit next to those nodes at the DC with you guys on the other end. So what do you think needs to happen to avoid this again?
And... last... when the advertising problem would be resolved, would another simple reboot not fix the current deployment?

**Comment by muhamadazmy** [comment]
yeah, I think there is somehting wrong with the network in this farm because before the node (after reboot) it tries to start the workloads it first wait for IPv6 for sometime before it give up and move on, assuming ipv6 is not available.

Then some workloads that requires public ipv6 fails (a VM that does not require Ipv6 will work normally). But it seems that later on IPv6 arrives finally (via router advertisement)  and then node accepts new VMs with Ipv6... Until the next reboot! 

Regarding if a reboot would fix affected workloads, the simple answer is No, here is why:
- When zos tries to run a workload and it fails, it sets the state to error and the cause of the error on the workload that failed.
  - Note that a deployment can have multiple workloads, and state is per workload. So a deployment can have some workloads in OK state (say, network, disks, etc..) while others in error (say a VM) 
- Once a workloads goes into error state, ZOS never tries to do it again, it's up to the user to check the error, see what need to be done (change the workload parameters, and update the deployment)
- This means that a simple restart won't force zos to fix the broken workload.

**Comment by shng4you** [comment]
Yes, clear. Got that. Still curious what Jan has to say about this. Maybe ZOS should be made a little less 'timing' sensible?

**Comment by muhamadazmy** [comment]
@delandtj any comments on this ?

**Comment by xmonader** [comment]
closing as too old
