### ISSUE TITLE
Node crashes with panic, redis.sock is missing

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/zos#1968]
Farmer reports that after adding a new storage controller, they see these errors and the node reboots:

![image](https://github.com/threefoldtech/zos/assets/17682591/ffaf24a7-b020-4b3f-9fc0-2ee241d46f00)

![image](https://github.com/threefoldtech/zos/assets/17682591/d3657224-36af-4345-a106-e483d3a86575)

Any ideas?

**Comment by muhamadazmy** [comment]
That's a super weird crash. this can only happen if somehow redis socket was deleted! any idea what is the node id was? it's not visible from the screen.

It's so weird also that the node reboots. nothing should reboot the node because of an error.

So if Node id and farmer id would be helpful to debug.

**Comment by scottyeager** [comment]
Farmer reports that both nodes 5201 and 4756 are showing this behavior.

**Comment by scottyeager** [comment]
There's another report from node 421. That farmer started seeing the issue after setting up the farmerbot, so potentiall there's some relationship there.

**Comment by xmonader** [comment]
should be fixed in this https://github.com/threefoldtech/zos/issues/1985
