### ISSUE TITLE
Network issue while running Farmbot

### ISSUE THREAD

**Issue by Ashishban** [threefoldtech/zos#1991]
Client has issue on his node which gets stuck while boot.  He is using farmbot and nodes dont wake up until he reboots.

There is nothing wrong on his logs as discussed with [scottyeager](https://github.com/scottyeager), so we asked him to share the image of his screen where the node stucks.

Below is the image - 

![whatsapp-image-2023-06-29-at-1_18d78e](https://github.com/threefoldtech/zos/assets/91247662/2820205c-1ebf-4e36-a94c-262627b30849)

Further, the hardware is reliable as per client. As he states - these machines were gold certified for 9 months and almost 100% uptime on all of them.

**Comment by muhamadazmy** [comment]
Sorry for late response, i was on a holiday. 

I don't get the part "nodes dont wake up until he reboots". Does this mean the node works fine if he reboot after it was stuck ? Or that it doesn't wake up via the farmer bot and then it get stuck ? Also what happens if he reboot it when it is stuck?

The error is not related to the node hardware. This error is coming from `0-fs` which is trying to connect to remote storage (the hub) to download some files for the packages. The error says `temporary failure in name resolution` is the cause. Basically it can't resolve the `hub.grid.tf` (so it's more of a network problem) 

The weird thing about the error above is that the node had no issue downloading the flists. it means the network is fine. 

I will make sure latest available image and flists are fine, but mean while please answer the questions above

**Comment by Ashishban** [comment]
Hi @muhamadazmy Yes, the node works fine after the reboot when it gets stuck. 

Screenshot shared above is the screen at which node gets stuck.

**Comment by muhamadazmy** [comment]
Again i wanna to make it clear that this is not a `storage device` issue but instead is a networking issue. It's weird that it is resolved after the node is rebooted. 

May be we can make it retry a little bit more when it fails

**Comment by Ashishban** [comment]
I communicated the above messages with the client and he states -

It's really a hassle now, since today I have 4 nodes with same type of issues. Once rebooted, no issue. But today seems downloads are really really slow and I know the connection is not the issue

<img width="284" alt="screenshot-2023-07-10-152403_ljyjm0" src="https://github.com/threefoldtech/zos/assets/91247662/c31ef767-6ad2-480a-a17a-760db342f957">
<img width="290" alt="screenshot-2023-07-10-152603_1wfk51b" src="https://github.com/threefoldtech/zos/assets/91247662/37d8f811-6af4-4aff-a4ee-864b3bb61a65">

**Comment by muhamadazmy** [comment]
A network issue does not always mean your infrastructure. It still can be a zos issue or remote server issue. But i just wanted to say it's not as the issue title suggests it's a `storage device` issue. but it's rather a connection from the node to the remote storage.

**Comment by muhamadazmy** [comment]
Also the download `is very slow` can indicate indeed a problem connecting to remote server. What is the location of the nodes and if you have good internet in general

**Comment by Ashishban** [comment]
Node location is Netherland and the client states "The machines where not using full bandwith for sure"

**Comment by shng4you** [comment]
The farmer stated that he still gets an error api-ws: disconnected from wss://tfchain.grid.tf/ws: 1006:: connection dropped by remote peer. Also, he noticed that the grid docker was restarted 4 days ago, and all others still have the same period of 12 days.

![whatsapp-image-2023-07-10-at-1_7cxfx8](https://github.com/threefoldtech/zos/assets/95933607/33217330-c886-4348-9171-1aa3dd6928cc)

**Comment by mahendravarmayadala93** [comment]
> he noticed that the grid docker was restarted 4 days ago, and all others still have the same period of 12 days.

The client shared the picture of Docker's environment where he's seeing the picture of containers 12 days up.

<img width="551" alt="screenshot-2023-07-10-182321_ok762r" src="https://github.com/threefoldtech/zos/assets/89931135/78919809-fc47-4d4b-aa70-f3acbf1af8a4">

**Comment by muhamadazmy** [comment]
The docker images and such are related to farmerbot not zos. I am more concerned regarding hanging on boot.

**Comment by muhamadazmy** [comment]
I still don't get why it fails because `temporary failure in name resolution`. Is it possible that DNS on this network is throttled (or rate limited) ?

We can introduce `retrials` on failure for sometime before giving up, but this will never grantee the problem is solved 100%

**Comment by brandonpille** [comment]
Could you also share the farmerbot logs? Just to make sure everything is ok there.

**Comment by shng4you** [comment]
> Could you also share the farmerbot logs? Just to make sure everything is ok there.
@brandonpille please see the Farmerbot log file here.
[Uploading farmerbot (4).log…]()

**Comment by shng4you** [comment]
> Could you also share the farmerbot logs? Just to make sure everything is ok there.
Please see the Farmerbot log file here.
[farmerbot (4).log](https://github.com/threefoldtech/zos/files/12013419/farmerbot.4.log)

**Comment by brandonpille** [comment]
> > Could you also share the farmerbot logs? Just to make sure everything is ok there.
> > Please see the Farmerbot log file here.
> > [farmerbot (4).log](https://github.com/threefoldtech/zos/files/12013419/farmerbot.4.log)

I can indeed see that it is not able to power it back on. All the rest looks normal.

**Comment by muhamadazmy** [comment]
@Ashishban can you ask the farmer to try to reproduce the issue. see if there are any improvements.

Also could you ask him if when this issue happens if there are multiple nodes booting at the same time.

Thanks.

**Comment by Ashishban** [comment]
Client states - There are multiple booting at same time. But it also happens when not multiple are booting at same time
So no real clue there And reproducing is hard, it just happens at random to say 2/3/4 nodes every day
But almost always an other node, never the same
And reboot normally issue gone.

Plus

Again 2 machines with same error.. also 1 machine with 2 new ones...

<img width="739" alt="2" src="https://github.com/threefoldtech/zos/assets/91247662/25fc522b-afca-4646-9fa6-f6ce7a53dbd8">
<img width="260" alt="1" src="https://github.com/threefoldtech/zos/assets/91247662/62e96282-7dcf-42b8-b80d-29e49acebc33">

Client also stated - And again.. got stuck 2x at loading drivers and now it boots without problem... so node 5960 missed the wake up as well.. and I have no clue. Also, not sure if coincidence, normally first booted nodes go to standby first, now the first 8 booted nodes whent to standby the last (aside from the one not booting properly)

**Comment by muhamadazmy** [comment]
there is definitely some network problem here. the internet in not stable. The last screenshot where zos is being downloaded happens in IPXE (there is no operating system running yet) and already see you have connection resets.

I assume those issues happend AFTER i asked you to retry? right ?

**Comment by maxux** [comment]
Can the user ensure different ip are offered by dhcp each time ? It sounds like same ip could be delivered to multiple node while booting, which could lead to ip conflict ?

Can we get output of differents node trying to boot, to see their mac and ip while being stuck (in ipxe for example) ? I don't know if that's the problem at all, but try to guess :)

**Comment by Ashishban** [comment]
Sure. Checking with the user on this.

**Comment by Ashishban** [comment]
Client states - Yes happened after retry, and I have no assumptions that netwerk was not stable, since all worked and all other machines booted fine as wel... the same node also.

All machines have other mac and ip adresses, they also get other adresses for zos.

Should I get a screenshot for confirmation?

**Comment by Ashishban** [comment]
Nodes affected : yesterday 5960, 5969, 5970, 
Today: 5959, 5962 and 5965

**Comment by shng4you** [comment]
> I don't know if that's the problem at all, but try to guess

Farmer says:  "No, as told, different addresses have to be due to the ILO console using separate addresses too."
https://192.168.2.32/ 3c:a8:2a:1e:a3:44
https://192.168.2.59/ 94:18:82:77:ce:2c
https://192.168.2.60/ 94:18:82:76:2f:ec
As per the farmer, below are the nodes affected
Yesterday 5960, 5969, 5970
Today 5959, 5962 and 5965

<img width="284" alt="Bootstrap" src="https://github.com/threefoldtech/zos/assets/95933607/b966682e-8799-4529-83ca-a5fc952a28f1">

**Comment by Ashishban** [comment]
We have an another user on Telegram (Mahi) with the similar issue.

![photo_2023-07-15_02-14-49](https://github.com/threefoldtech/zos/assets/91247662/8c3993e9-e0f7-41e5-bc7d-2b326f55e63f)

**Comment by scottyeager** [comment]
This latest screenshot shows a slightly different error message: `Temporary failure in name resolution` versus `No address associated with hostname`

I also wanted to forward some info from the farmer who sent this screenshot on the troubleshooting steps they took and the fact that the issue started suddenly in a stable environment:

> i tried a couple things...
> new cables between switches,
> changed the switches also,
> reconfigured the subnet
> switched from pfsense to windows DHCP server and increased the range
> downloaded the pxe file again
> monitoring the network for bottleneck => no issue
> but still every periodic wakeup 4-5 random nodes get stuck 
> 
> and to be clear, i didnt do anything at least 5days before the issue started, so i am guessing it is something with ZOS

**Comment by amandacaster** [comment]
@muhamadazmy can you please share your thoughts based on the above comments?

**Comment by Ashishban** [comment]
Client is chasing an update. Please share an update.

**Comment by muhamadazmy** [comment]
There is nothing i can do about this issue from zos perspective:
- First, the system is not booted yet, this is the first stage of bootstrap where we only download packages
- At this stage the system has not setup any advanced networking yet, so the system is basically using whatever has set up over dhcp (gateway, dns, ips, etc...)
- All the above issues are related failure in name resolution (hence DNS) 

What i would do is:
- Make sure dns is okay, and that it's up and running
- Make sure that there is only one dhcp running on that network

**Comment by Ashishban** [comment]
Client states -

Thats not entirely true, I see often this error appear at the latest downloads from the stages. So it already has a connection for quite some time.

I know multiple people from just 4 to 50+ servers who experience this error at random.

DNS is okay, there is just one DHCP, I even put down vlans and just running one network.

Bios is up to date, same as clock. But reboot does always fix it, so if there should be issues with bios or clock, it should be every time, which is nobody's case.

He adds:

I spoke to other guys who also said it just came suddenly, while before it was working

And it can't be something like bios/clock, because then reboot would not fix it

**Comment by Ashishban** [comment]
Client even states - Pings always work, use them myself to check for wakeups working...
IP's are connected to my management console as way, Ip's haven't changed since day one

And still.. not logical that all people would have that issue, every day, with every machine, no matter how big or small the farm...

And, also, no issues in past

With same equipment, no changes there as well

**Comment by scottyeager** [comment]
So, just to recap what we know so far:

* This issue affects multiple farmers in different countries (so not ISP related)
* One farmer has changed out basically every component in their network that could be responsible, including the router
* These farmers report that their setups were working previously with the same configuration (seems something changed that brought the problem on for them more or less simultaneously)
* This happens with 8.8.8.8 configured as the DNS server (so not an issue of an unreliable ISP provided DNS)
* Sometimes the problem happens at the initial bootstrap phase and sometimes it happens later in the boot process

It seems reasonable to conclude that the source of the issue is not Zos itself, but I also don't think we can conclude that the farmers' networks are solely responsible. What other explanations can we explore here?

**Comment by muhamadazmy** [comment]
Okay, i will review latest changes to see what can cause such an issue.

**Comment by muhamadazmy** [comment]
I think i have found the issue, it seems that in the package repo there was an lingering old package of 0-fs that overrides the latest 0-fs build. in other words the node was downgrading 0-fs while booting hence causing it to fail to download next packages. 

I made sure to clean this up, now the node should only be able to update 0-fs.

I will also make sure that the base image has the latest 0-fs build and not wait for boot to update itself this will make sure we have the latest builds faster (this might take a while)

But since the broken package is gone from the repo, can you try to restart the node and see if it goes throw this time? Note that the image version is still kinda behind but hopefully not old to cause this issue again.

**Comment by scottyeager** [comment]
We have asked affected farmers to let us know if the issue persists.

**Comment by muhamadazmy** [comment]
Also images has been rebuilt with latest 0-fs built in, so it will be available during early boot stages. Let me know when u have any feedback. thanks

**Comment by scottyeager** [comment]
Good to know, thanks. So far I've been in touch with one farmer who says the issue seems to be resolved since the outdated flist was removed. Support team is following up with a few others and we'll update here as more reports come in.

**Comment by muhamadazmy** [comment]
@Ashishban please feel free to close the issue if u think the issue has been resolved, thank you :)

**Comment by Ashishban** [comment]
Closing ticket as the chat has been marked resolved.
