### ISSUE TITLE
`gpu.list` returns an incorrect GPU device

### ISSUE THREAD

**Issue by AbdelrahmanElawady** [threefoldtech/zos#1994]
Using https://gridproxy.dev.grid.tf/nodes/93/gpu to query GPUs on node 93 shows a device name of `Navi 31 [Radeon RX 7900 XT/7900 XTX]` as the GPU on the node.
However, `RX 7900 XT` is a different than `RX 7900 XTX` https://en.wikipedia.org/wiki/Radeon_RX_7000_series. So, it should only return one of them (the one used).

**Comment by AbdelrahmanElawady** [comment]
According to PCI IDs [repository](https://pci-ids.ucw.cz/mods/PC?action=help?help=pci) the ID is separated into vendor, device and subsystem. For some GPUs device ID is not enough to identify the GPU and subsystem ID is used to identify it.
For example:

SSID doesn't cover all variations of the card:
```
	744c  Navi 31 [Radeon RX 7900 XT/7900 XTX]
		1da2 e471  NITRO+ RX 7900 XTX Vapor-X
		1eae 7901  RX-79XMERCB9 [SPEEDSTER MERC 310 RX 7900 XTX]
```

SSID for both variations:
```
	1e78  TU102GL [Quadro RTX 6000/8000]
		10de 13d8  Quadro RTX 8000
		10de 13d9  Quadro RTX 6000
```

So, using SSID will further improve determining what GPU is used. However, SSID data is not well maintained so it won't cover all GPUs.

**Comment by muhamadazmy** [comment]
Yeah, i was gonna comment exactly that on the issue but you already came to the same conclusion. The problem is the system only expose the Vendor and Device ID. while the db already has a list of (sub devices) i couldn't find the sub-device id exposed by the system hence it was not possible to identify

That being said, All devices that has the same device ID are used exactly the same way (with same drivers and everything) while they are different they should expose the same `interface` and be used the same way.

So there might be differences but it shouldn't be big enough to be identified as a different device.

**Comment by muhamadazmy** [comment]
Just notices, there is a PR to do exactly that, i will take a look. thank you

**Comment by AbdelrahmanElawady** [comment]
actually in some cases the difference is double the VRAM in `Quadro RTX 6000/8000` example. 6000 has 24 GB VRAM while 8000 has 48 GB VRAM and that could affect users needs a lot.

**Comment by muhamadazmy** [comment]
I am wondering if we really actually need to "make" a difference because they use the same `chip`. 
For example, my nvidia card subsystem_device is not even listed on the pci database, (only the device) while the subvendor is `dell` the vendor is NVIDIA. IMHO adding the subsystem vendor and device does not add much. 

But i assume this issue was raised based on some context that i am not aware of, so let me know why this is needed then we can decide how to proceed.

**Comment by AbdelrahmanElawady** [comment]
the context of this issues is that currently node 93 with `AMD Radeon RX 7900 XT` reports a GPU: `Navi 31 [Radeon RX 7900 XT/7900 XTX]` which are two different GPUs, and that case will happen in GPUs that share the same Device ID. The issue isn't exactly with GPU drivers but with the GPU compute power. In many cases the GPUs are different in performance and can vary greatly. using SSID further improves the identification (if it exists in db) so user will know exactly how if it will fit their requirements.
SSID (with Subsytem Vendor) should be unique to each GPU however the DB doesn't contain all of them but it will improve for GPUs with SSID in DB.
