### ISSUE TITLE
GPU card keeps reserved for more than an hour after deleting the contract

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/zos#2008]
env: devnet
node: 93

when calling`zos.gpu.list`, the contract's field is not 0 after deleting the contract for an hour.

Related: https://github.com/threefoldtech/tfgrid-sdk-ts/issues/818

**Comment by xmonader** [comment]
While checking it seems the Storage capacity isn't cached https://github.com/threefoldtech/zos/blob/cf9e816109a9dc0baf3a445aa8c39146cbef92ea/pkg/provision/storage/storage.go#L683 so that looks okay

So next thing is the cleanupDeleted routine in provisiond https://github.com/threefoldtech/zos/blob/cf9e816109a9dc0baf3a445aa8c39146cbef92ea/pkg/provision/storage/storage.go#L740 I'm assuming is getting blocked or failing in the background, could be a good starting point to investigate the issue

**Comment by muhamadazmy** [comment]
Important question is: Does the VM (contract) that owned the GPU stays reachable/active for an hour after it's cancelled ?

**Comment by xmonader** [comment]
3.8.2 now has this fix https://github.com/threefoldtech/rmb-rs/pull/144

**Comment by khaledyoussef24** [comment]
now after deleting the gpu machine when `callingzos.gpu.list`, the contract's field is 0 in the same instant
