### ISSUE TITLE
Ensure proper nodeID loading in ZOS

### ISSUE THREAD

**Issue by mik-tf** [threefoldtech/zos#2020]
Hector on the TG farmer channel mentioned a persisting issue with ZOS not loading correctly the node ID.

Here is the [message](https://t.me/threefoldfarmers/64391).

"when loading node IDs: for context, in R620s with multiple identical disks, ZeroOS will not always use the same disk, which sometimes results in all my nodes booting correctly, and others like today, 80% of my R620 loading the wrong disk and needing one reboot or more to load the "main" disk."

Proposed fix by Hector: " if any SSD has a node ID, use it and don't register a new one. "

**Comment by priethor** [comment]
This becomes even more necessary when introducing [random wakeups in farmerbot](https://github.com/threefoldtech/farmerbot/pull/45), as there's a 50% chance those wakeups will fail at any time of the day, any day of the week.

**Comment by priethor** [comment]
> there's a 50% chance

It's worth noting that even in 3+ SSD nodes, only the first two SSDs get to load: I haven't experienced any node registering an ID in the third or more SSD, only the first two "win the race", hence me saying 50% chance regardless the number of SSDs.

**Comment by muhamadazmy** [comment]
ZOS uses the first disk that is marked as cache always. it never tries to use another disk unless it couldn't find the `main` disk. 
the way zos `finds` the main disk is that it tries to scan all SSD disks (as detected) and then try them one by one until it finds a disk with special subvolume that is used to store the id and cache information. If none of the disks has this, it then it assumes a fresh boot and generates a new id picking a disk at random (from the ssd disks)

This means ZOS will ONLY have possible (random) multiple ids if and only if multiple disks has IDs subvolumes on them. and this won't happen (as explained above) unless zos failed to detect one of the node disks as SSDs at some point. Or unless the disks has been backedup or copied manually by someone at somepoint.

I assume in the issue that the node does not just create a completely new ID each time it boots and that it rotate some set of static IDs. (because the way it  tries disks are not predictable). 

This means the fix suggestion by Hecktor is not valid, because that's basically exactly what the node does. An actual fix is that disks with wrong keys need to be `cleaned` by deleting only invalid keys subvolumes.

This is easier then done, because a user who tries the boot the node with ubuntu for example won't be able to find out which key is registred with the wrong ID.

If my assumption above is correct (that the node does not generate a new id everytime but instead just rotates a set of ids) then I can provide a tool that u can use to figure out which key is witch and help you remove the wrong one(s)

**Comment by muhamadazmy** [comment]
Note, the wrong detection could have happened because of an old bug that is not there anymore. So hopefully cleaning the disks that has the wrong keys work

**Comment by priethor** [comment]
> If my assumption above is correct (that the node does not generate a new id everytime but instead just rotates a set of ids) then I can provide a tool that u can use to figure out which key is witch and help you remove the wrong one(s)

Thanks for the detailed answer, @muhamadazmy. The node does indeed rotate between IDs, but I have tried in the past wiping all SSDs except one via `wipefs -a` and ZOS ended up registering a new node ID anyway; that's why I don't wipe it anymore and let it rotate. Example:
- SSD `A` has node ID `1`, and SSD `B` has node ID `2`.
- I remove SSD `A` and wipe SSD `B`
- I insert back SSD `A`. Upon next boots, ZOS will load either node ID `1` or register a new ID `3`

**Comment by muhamadazmy** [comment]
this sounds like zos really does not like SSD `A` . Note that zos does not use the `ROTA` information reported by the disk (zos does not just believe it) it actually run some speed tests. If the disk speed is below a certain speed it will sort it out as HDD not SSD even if the hardware says that it's SSD.

**Comment by priethor** [comment]
Both disks are the same brand and size, and it happens in all my nodes with either Samsung 870 QVO or Crucial BX500 (never mixed, only a model per server) installed on the first two bays.

If ZOS doesn't like those specific drives installed on the primary bay (`A`), I'm surprised it registered their node ID the first time I booted the servers with many SSDs installed 😞 . I could try and "bet" for the other drive `B`, switching `A` and `B`'s places to make `B` the main drive and, eventually, wipe `A`, but it doesn't seem it would solve the issue as the fail/success rate is around 50%, it's not that ZOS is usually loading `B` over `A` 🤔

**Comment by muhamadazmy** [comment]
what is the current node-id used by the node now ? I can try to see if i can debug it and see what shows

**Comment by priethor** [comment]
These are the nodes and their IDs (the originally registered in SSD `A` vs. the one that boots randomly even after I wiped disk `B`, and their shared SN):
- 2222 vs. 5692 (SN 3TXJN22)
- 2223 vs. 5694 (SN 2Y5LN22)
- 2224 vs. 5697(SN FQQLV12)
- 2225 vs. 5732 (SN FGX6P22)
- 2226 vs. 5695 (SN CBQXFX1)

**Comment by priethor** [comment]
As a note, today nodes 5692 and 5695 booted, and they didn't recognize all SSD capacity: the "failing" SSDs appear as HDDs

**Comment by muhamadazmy** [comment]
Can i ask you to do something for me. Can u boot this node (the one with all ssd capacity not recognized) with an ubuntu live usb (or any linux distro you like) then you can run the seektime tool we use in zos here https://github.com/threefoldtech/seektime

You can run it multiple times and see if the values changes as well.

**Comment by scottyeager** [comment]
I have detailed instructions for how to run `seektime`, along with a precompiled binary [here](https://forum.threefold.io/t/testing-ssd-health/3436). The disk utilities GUI program in desktop Ubuntu also has a seektime diagnostic that could help to provide some insights.

**Comment by priethor** [comment]
Just circling back here to acknowledge I haven't been able to run the tests yet and won't be in the next few days, but it's on my to-do list. I'll get back to you ASAP 🙂

**Comment by priethor** [comment]
👋 Hey hey!

I finally got to run some tests on server `2222`, the one giving me the most booting issues, and the results make quite a lot of sense.
- Disk A (the "primary one" that often seems to fail) has a seek time between 110 and 130us, with some peaks of 140us.
- Disk B, on the contrary, has its normal distribution (at a simple glance, not scientific) between 100 and 110us, with some peaks of 125us.

This explains a lot about why disk B is the one being loaded many times. Both disks are CrucialBX500 2TB. The rest of the tests showed equal results for both drives.

**Comment by scottyeager** [comment]
Thanks for the update, @priethor.

It's definitely interesting to see that there are some higher seek times on the disk that seemed to be cause the most trouble. However, this doesn't fully explain it, since the `seektime` utility is looking for a time under .5ms (500us) to detect as SSD. So there must be something extra happening to push the averages up on the boots where detection is incorrect.

I should mention here that a change was deployed to mainnet in the last release to persist the disk type after initial detection, so we shouldn't see the issue of SSDs later being detected as HDD anymore (assuming it's properly detected when disk type is persisted).

**Comment by priethor** [comment]
On the other hand, I ran the same tests on node 2226, which usually boots well and loads the node ID from the right SSD (today it didn't 🙃 ). Both run Samsung 870 QVO SSDs, and these are the results:
- Disk A (4TB), shows seeking test results of around ~200us on average.
- Disk B (500MB), shows ~25us seeking time on average.

These results are not surprising considering the disk sizes but are confusing since zero-OS usually loads Disk A indeed.

**Comment by priethor** [comment]
> I should mention here that a change was deployed to mainnet in the last release to persist the disk type after initial detection, so we shouldn't see the issue of SSDs later being detected as HDD anymore (assuming it's properly detected when disk type is persisted).

Thanks! I saw the update and I'm wiping all B-disks to test the new update.

**Comment by scottyeager** [comment]
> but are confusing since zero-OS usually loads Disk A indeed.

The seek times are only used to determine disk type, not to order the disks for priority in selection for which is the cache. So we can say that while the 4tb Samsung has a higher average seek time than the Crucials, whatever is causing the seek time results to sometimes come in above .5ms is not happening (as often) for the Samsung, whether that's caused by the drive itself or something else in the system.



> I'm wiping all B-disks to test the new update.

Sounds good. Keep us posted on the results.

**Comment by priethor** [comment]
After today's programmed farm wakeup and a couple of manual wakeups, this issue hasn't been reproduced anymore, and all nodes have loaded their existing node ID. This is the most consistent node loading ever (especially since using the farmerbot; before, it wasn't really an issue as nodes didn't usually turn off/on)!

I think we can close the issue -knocks on wood- and revisit it later if we spot anything similar.

**Comment by priethor** [comment]
After a whole week, I can confirm that all node wake-ups have worked flawlessly; this issue is definitely fixed and ready to be closed. ✅ 

Thanks, team!

**Comment by mik-tf** [comment]
Thanks @priethor for the feedback.

@muhamadazmy @scottyeager 
I am closing the issue. Feel free to re-open if you think it's necessary.
