### ISSUE TITLE
[api4] [rpc] design RPC endpoint to replace Deployment struct with CRUD

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/zos#2059]
Sub of: https://github.com/threefoldtech/home/issues/1468
The idea is that instead of working with a single `deployment` endpoint that deals with a full deployment that we instead do smaller and separate transactions to create/modify/and delete components :

- v4/zos.project(`<project>`)
- v4/zos.project.list() -> projects for the user that made the calls 
- v4/zos.`<project>`.disk.create()
- v4/zos.`<project>`.network.set(`<data>`) where data is the network config
- v4/zos.`<project>`.vm.create(`<data>`) but this for example wont' work unless the network is set 
- v4/zos.`<project>`.vm.`<name>`.restart() 
- ...

> TO BE SPECED in json rpc

**Comment by rawdaGastan** [comment]
# Drafted ZOS APIv4 design


The idea is that instead of working with a single deployment endpoint that deals with a full deployment that we instead do smaller and separate transactions to CRUD operations for components

## Main RPC endpoints

Users can create any project with a specific name that includes any existant compnents 

- `v4/zos.project.get`  (project name) -> gets a specific project using its name 
- `v4/zos.project.list` -> lists all projects for the user that made the calls 

### Project data

- Name
- Twin ID
- Contract ID
- Metadata
- Description
- Expiration
- SignatureRequirement

## Endpoints for components

- `v4/zos.project.<component>.create`  (project name, component date) 

- `v4/zos.project.<component>.restart`  (project name, component date) 

- `v4/zos.project.<component>.get`   (project name, component name)

- `v4/zos.project.<component>.update`  (project name, component data)

- `v4/zos.project.<component>.delete`   (project name, component name)

### Components

- network
- VM (fails if no network is created for the same project)
- disk
- zdb
- qsfs
- zlog
- zmount
- fqdn gateway
- name gateway
- public ipv4

### Component data

- Version
- Name
- Project name
- Metadata
- Description
- Data 
- Result

**Comment by rawdaGastan** [comment]
For RPC json: [apiv4.md](https://github.com/threefoldtech/zos/files/12659126/apiv4.md)

**Comment by muhamadazmy** [comment]
Can you create a branch and add rpc under docs instead of attaching the file to the issue please, this way we can comment and contribute

**Comment by muhamadazmy** [comment]
@rawdaGastan can you redo this with openRPC instead? jsonRPC does not define types which is a problem.

**Comment by xmonader** [comment]
@despiegk this has been > month without progress? should it get moved to 3.14 or we accept the currently provided design?

**Comment by muhamadazmy** [comment]
I think shis should be for version 4. Last i heard is @despiegk was working on the api draft in V where then we can adabt and implement in zos.

**Comment by xmonader** [comment]
closing in favor of https://github.com/threefoldtech/home/issues/1468
