### ISSUE TITLE
Nodes aren't responding over RMB (to be verified on mainnet)

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/zos#2060]
Since the update to Zos `3.8.4`, we have additional reports of nodes not responding over RMB. These are coming from farmers who notice that the farmerbot is not properly managing their farm because it cannot detect that nodes have woken up.

## Farm 3074

Of the nodes in this farm, only the one set to `never_shutdown` is reachable over RMB. As of the tests I ran (RMB ping using `zos.statistics.get` and also attempting to deploy a workload to the node), power target and state was `Up` for all nodes, they were reporting uptime within normal boundaries, and no errors are seen on Loki logs.

**Nodes not responding**
3509
3982
3514
3688
3796
3505
3510
3512
3517
3504
3515

**Nodes responding**
3518

The farmer rebooted all nodes on Friday, and only one node, 3510, was successfully power managed over the weekend. 

While investigating the issue today, the farmer also rebooted seven nodes in this farm. Of the seven, only four started responding over RMB after coming back online.

**Nodes rebooted**
3512
3514
3515
3517
3688
3796
3982

**Nodes responded after reboot**
3512
3514
3515
3982

**Nodes not responding after reboot**
3517
3688
3796

node 3504 started responding again over RMB after a reboot (replies were delivered for all pending messages). So this implies that nodes can have a period of normal operation after reboot and then RMB fails later.

## Farm 197

This is @Mik-TF's farm. He didn't try rebooting any nodes.

**Nodes not responding**
580
582

**Nodes responded (these nodes also have workloads)**
3860
577

**Standby nodes (responding as of last farmerbot wakeup cycle)**
879
880
654
581

**Comment by muhamadazmy** [comment]
We still think there is an issue with the `rmb-peer` process on the nodes. The issue is impossible to reproduce locally but it still happens in the wild (given the huge number of nodes). We run all kind of tests, stress tests, loss of connection from both sides, and code reviews many times to see if there is a possibility of a race or something in the code that might get the peer in such situation with no results so far.

I really think the issue might be in the low level websocket libraries we are using, what we going to do next is make sure we update to the latest libraries and update mainnet

**Comment by scottyeager** [comment]
Thanks for the update, Azmy. Let us know if there's any additional info we can collect that might be helpful.

**Comment by A-Harby** [comment]
## Farm 3074
It show all the nodes online,
![image](https://github.com/threefoldtech/zos/assets/109473873/70b76fb4-3d17-4b12-b1c8-c09d680ceabc)
But when I ping them using grid ts client, only the Nodes 3796 and 3518 are the node responding.  
![image](https://github.com/threefoldtech/zos/assets/109473873/dd825eb8-ad84-4503-9d73-3f269fd1dcfa)

## Farm 197
It show some of the nodes online and some are on a standby,
![image](https://github.com/threefoldtech/zos/assets/109473873/457cd1e9-5535-45db-b41e-9bf62f295d45)
![image](https://github.com/threefoldtech/zos/assets/109473873/49cbdeb7-cd9c-4632-9065-11c05af0b1cc)
But when I ping them, only the Nodes 577 and 3860 are responding. 
![image](https://github.com/threefoldtech/zos/assets/109473873/c94d5eb0-3ed6-49d2-9430-f158b4811260)

**Comment by muhamadazmy** [comment]
we will have to wait on this until the latest version is on mainnet

**Comment by scottyeager** [comment]
Hi @ramezsaeed, aren't we still waiting for release of 3.12 to mainnet so this can be verified?

**Comment by xmonader** [comment]
I will keep this and the rmb-rs (the root cause issue open) to verify after mainnet deployment

**Comment by khaledyoussef24** [comment]
some nodes are giving me a up status but they are not responding over the rmb calls 
<img width="1680" alt="Screenshot 2024-01-30 at 5 46 46 PM" src="https://github.com/threefoldtech/zos/assets/110984055/bbb9cd84-18cf-40b6-8c39-e25616824b9d">
<img width="1227" alt="Screenshot 2024-01-30 at 5 54 23 PM" src="https://github.com/threefoldtech/zos/assets/110984055/71cf021f-fe5c-44dd-b9aa-41e4c4b22295">
i even increased the time out to 100 seconds instead of 10 seconds but still no response
