### ISSUE TITLE
integrate mycelium in zos

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/zos#2073]
https://github.com/threefoldtech/mycelium

**Comment by muhamadazmy** [comment]
Is this gonna replace yggdrasil completely or will be running side by side with yggdrasil for now ?

**Comment by muhamadazmy** [comment]
There are lots of consideration here about the decision of if we replace and or work next to yggdrasil:

- Both decisions will still require a lot of work regarding networking.
- Replacing yggdrasil will break backward compatibility, running VMs with yggdrasil IPs will suddenly become unreachable because the entire planetary network range will be different.
- Running both of them will also complicate things since we will have to maintain 2 planetary networks with 2 different ranges, set of peers, etc... and then VMs can then choose to be part of mycelium network, yggdraisl or both.
- There is no way we can keep backward compatibility without supporting both yggdrasil and mycelium (hence dragging a lot of code) for a long time (may be forever)
- ZDBs are also reachable over yggdrasil which means dropping ygddrasil will mean that zdbs will now have new IPs. 


I personally would like to drop yggdrasil, and use mycelium network for all nodes. Do some work to update the running VMs Ips (will probably require a restart of the VMs to force using a new ip with cloud-init) and notify the community about the change. Hence they can get the new IPs from the nodes

Nodes can instead also decide to restart fully instead to drop yggdrasil and all related setup to switch fully into mycelium

**Comment by muhamadazmy** [comment]
Blocked on https://github.com/threefoldtech/mycelium/issues/33

**Comment by xmonader** [comment]
This won't be feasible in 3.13, moved to 3.14 until that's settled

**Comment by muhamadazmy** [comment]
After researching and collecting all the requirements here what we going to do:
- mycelium will run (upon the user request) per user network. a follows
- the network workload can have an optional mycellium key witch is a hex encoding of a 32 bit seed (that will become the mycelium key)
- if required, the Network Resource for the user network gets the following:
  - a bridge `br-my`
  - start mycelium under the network resource creating an interface `my0` 
  - the bridge is given the IP `<network>::1/64` of the mycelium network
  - make sure the bridge is brought up (this can require to plug something into the bridge and can be a dummy interface)
  - mycelium is started and monitored via zinit
- If a VM is created then in this network that requires a mycelium IP:
  - A new tap is created, and plugged into the br-my (which lives inside the network resource namespace)
  - the tap device is then moved to the host network 
  - the tap device is attached to the VM 
  - the cloud-init config of course need to be added to the bootstrap disk
 - Note that ygg + my are mutually exclusive and cannot be used together for the same VM
