### ISSUE TITLE
inconsistency in the RMB calls for the new added test calls

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/zos#2115]
- some use camel case and others use snake case (used to get snake case from zos calls)

```
{ name: 'PublicIPValidation' },
{ name: 'CPUBenchmark' },
{ name: 'iperf' }
```

- to get one of the tests only, we can use `zos.perf.get` with the test name as the payload (payload: `'"iperf"'`), I think it would look nicer if the payload becomes `{"name": "iperf"}` and to be consistent with the rest zos calls

**Comment by muhamadazmy** [comment]
I suggest we use `Kebab case` instead of camel case it looks better in `json` keys
- `public-ip-validation` 
- `cpu-benchmark` 
- `iperf`

Also can you add a `Description` method to the task interface that has description of the test, and explain the results. Means that all tasks need to return a meaningful description

**Comment by khaledyoussef24** [comment]
verified by running the rmb call get.perf.all
names changed from
```

{ name: 'PublicIPValidation' },
{ name: 'CPUBenchmark' },
{ name: 'iperf' }

```

to

```
    "name": "public-ip-validation",
    "name": "iperf",
    "name": "cpu-benchmark",
```

description is also added to the response of the rmb call
