### ISSUE TITLE
perf get all command "zos.perf.get_all"  returns 2 public ip validation records

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/zos#2141]
## Describe the bug

perf get all command "zos.perf.get_all"  returns 2 public ip validation records with diffrent time stamps

## To Reproduce

run rmbcall with command "zos.perf.get_all" 

will print
```
 "description": "Runs on the least NodeID node in a farm to validate all its IPs.",
    "name": "public-ip-validation",
    "timestamp": 1701151202
```
the first one with the latest timestamp

```
 "description": "",
    "name": "PublicIPValidation",
    "timestamp": 1700546400
```

with a old time stamp a week ago

the  same goes for bench cpu test also
with two different name
2 time stamps for two tasks with 
  ```
  "name": "CPUBenchmark",
    "timestamp": 1701151205   4 hours ago

    "name": "cpu-benchmark"
    "timestamp": 1700546405   7 days ago
```

**Comment by muhamadazmy** [comment]
Ah i think because we renamed the tasks so it will keep the `old` task with the old name forever in redis. but that is totally safe to ignore

We can ignore this for now since i think only devnet will have this issue since this feature is still not on mainnet. Hence mainnet will only have the new names (the ones with the `-` in the name)

**Comment by muhamadazmy** [comment]
I will close as won't fix
