### ISSUE TITLE
failed to create flist mountpoint: disk quota exceeded

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/zos#2147]
I tried to create a full VM (Ubuntu 22.04, 25gb disk) on node 13 on testnet. First I saw this error:

```
workload vm within deployment 26953 failed with error:
failed to write image to disk: failed to write disk image:
read /var/cache/modules/flistd/mountpoint/81-26953-vm/image.raw: input/output error
```

Then on subsequent attempts I see this error:

```
Error: Failed to deploy zmachine with name diskfulltest on node 13 due to: 
failed to mount flist: 81-27043-diskfulltest: ro mount of flist failed: 
failed to create flist mountpoint: mkdir /var/cache/modules/flistd/ro/e4b87e423369bbd1a5550a1ca99a69a6: 
disk quota exceeded
```

Node should have plenty of SSD available:

```
zos.statistics.get
"total":{"cru":24,"sru":512110190592,"hru":9001778946048,"mru":202800123904,"ipv4u":0},
"used":{"cru":4,"sru":192199786496,"hru":0,"mru":37258554982,"ipv4u":0},
"system":{"cru":0,"sru":10737418240,"hru":0,"mru":20280012390,"ipv4u":0},
"users":{"deployments":8,"workloads":10}}',

zos.storage.pools
{"name":"f9daa031-4908-4120-af85-2f84038f53bd","type":"ssd","size":512110190592,"used":192241729536},
{"name":"c36c54c1-1f13-4fa0-b47a-04a964f16cbb","type":"hdd","size":3000592982016,"used":0},
{"name":"616d67b0-14c1-400e-8a44-0472f3ac8de6","type":"hdd","size":3000592982016,"used":0},
{"name":"77b5fc9d-8785-4a4b-8733-452c22dc9700","type":"hdd","size":3000592982016,"used":0}
```

Seems maybe Zos has filled available cache and is failing to allocate the next 5gb?

**Comment by scottyeager** [comment]
Update on this one: the issue was transitory and I've since been able to deploy to this node again. Nothing notable in the [logs](https://mon.grid.tf/explore?orgId=1&left=%7B%22datasource%22:%22Loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnetwork%3D%5C%22testing%5C%22,node%3D%5C%225Hc7S4BtoYafxhx4RWYnyArQ8iPCrvhvpCz9L2AwVwuKPx3D%5C%22%7D%22,%22maxLines%22:5000%7D%5D,%22range%22:%7B%22from%22:%22now-12h%22,%22to%22:%22now%22%7D%7D) to explain the why it started working again, but there's plenty of log evidence  that the issue was occurring.

**Comment by muhamadazmy** [comment]
The catchy part is actually this error is this one 

```
failed to create flist mountpoint: mkdir /var/cache/modules/flistd/ro/e4b87e423369bbd1a5550a1ca99a69a6: 
disk quota exceeded
```

- This just creates an empty directory on the `cache` subvolume.
- The cache subvolume is limited in side to around 5G by default. So even if the SSD disk has plenty of state we usually limit the cache.
- The cache ALSO auto resize if it start to hit the limit, All what i can think of is during the `download` of the raw image (first attempt) the cache started to fill up until it couldn't download any more chunks, and then you get IO error.
- The second attempt failed to even to create the mount directory since cache already "full" (only the subvolume is at it's limit)
- later the cache checks kicks in and expand the limit, thus later attempt passes

## Procudure 
The problem is now that the checks for the cache size runs every 30 min, that is not too fast. So after the first failure, it was around (worst case) 30min before the node corrects itself.

- A decision is made to enlarge the cache if it hits 80% of it's limit. 
- A decision is made to shrink th ecache if it is below 20% of it's limit.

May be for a fix:
- Do checks more ergulary (say 5 min)
- Enlarge if cache hits 60% 

This won't grantee during downloading of a big image like the raw.image in your case won't quickly fill up the cache faster than the cache health checker. but:
- Using of full vm image should be depreicated (it's shame that official images still uses this method)
- This chances that this issue happes should be less common

The reason we have a limit on the cache is that it makes the capacity calculations much faster since the SSD is shared between many things, its' faster to assume the entire cache is using that "quota" thatn actually checking how big it is by checking the total sizes of the files. This way we can say that we have enough space to deploy a disk for example much faster than doing the scan

**Comment by scottyeager** [comment]
Thanks for the explanation @muhamadazmy.

I think the steps suggested make sense to help keep the node in a state where it can receive a reasonably sized raw image without hitting the cache limit.

That's interesting to know that avoiding raw images can help with this problem. While I'm not sure we should remove the functionality, I can certainly help with seeing that the "set of files" based approach is preferred in our documentation and official images going forward.
