### ISSUE TITLE
Check delay in node uptime reports

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/zos#2159]
In the current minting there are occasions where the nodes take more than 40 minutes to send uptime. In these cases, the nodes won't receive tokens for the window past 40 minutes (actually 41 - we allow 1 minute of slippage for blockchain related stuff).

This is a tracking issue to verify some of these nodes, as it is possible that these are actually valid cases. I.e. if a node can't reach the internet, it is considered to be down and not operating on the grid (after all you can't deploy on it during this time), so the node should not get uptime credited for this time either. 

CC @sabrinasadik

**Comment by muhamadazmy** [comment]
A subset of the nodes that has this issue (with possible uptime window) would be nice so i can investigate what might be the cause

I assume you calculate the 40 min delay from the latest valid uptime, right ?

**Comment by muhamadazmy** [comment]
Okay, so I checked the list of nodes where those "delays" in the uptime reports showed up and i picked few random ones to investigate. 

All the ones i checked they always reported networking issues that showed up in their logs during the time windows of the "delayed" reports.

## For example (screenshot from one node logs)
![image](https://github.com/threefoldtech/zos/assets/10920323/cf1436bf-f760-416d-bb63-2ef1b76e24ab)

It is clear that the node had network issues during this time. The node still manages to report the uptime and push the pending logs over after network issue was resolved.

It's also clear that this issue is local to the node, because the grid endpoints are monitored and we did not receive any alerts during the reported windows.

**Comment by sabrinasadik** [comment]
Ok so nothing on our side then. Let's close the issue? @LeeSmet

**Comment by LeeSmet** [comment]
Sure
