### ISSUE TITLE
Node booted up and went back to a black screen.

### ISSUE THREAD

**Issue by shng4you** [threefoldtech/zos#2178]
The node boots it up and downloads the zos successfully, and the screen stays black, and nothing happens. Also, the node ID (1617) does not appear/online in the explorer/dashboard.

https://github.com/threefoldtech/zos/assets/95933607/137f1f44-fd9a-44e7-924b-ebd456483805

Here is the screenshot of the log file after pressing alt-f2 after the screen goes black.

![Afbeelding van WhatsApp op 2024-01-04 om 09 18 04_15706169](https://github.com/threefoldtech/zos/assets/95933607/61332c7d-7e62-45c3-b7be-c6d65f8b8495)

The farmer changed the router, changed the NIC card, and upgraded the firmware, but the issue remains the same.

Also, as per the farmer network description:
Node 1617 - Z440  - Home Net - Down
Node 2163  - Titan - Home Net - Up
Node 1665  - Lenovo ThinkCentre BIG - Up - Network at the office (different location)
Node 3236  - Lenovo ThinkCentre Small - Up - Network at the office (different location)
Node 3594 - Z840 - Down - Network at the office (different location)

**Comment by scottyeager** [comment]
We should also note that the farmer has let the node run for some time like this (up to a day or more) and it does not progress.

**Comment by TullysInc** [comment]
The last update we received from the farmer was:

1. Node 1617 - changed to 6268: status - up (it appears he wiped/replaced the disks for this node).
2. Added a new node - 6275: status - up.

The IDs listed below are the ones he wanted to remove from the system entirely (which we advised is not possible to delete). So we can understand from this the 2 expected nodes are reporting Up as required. I believe we can close this issue since it has been resolved.

IDs intended to delete:
1567
1593
1617
3594
3698
6144
