### ISSUE TITLE
Can't use same GPU card after deleting its vm

### ISSUE THREAD

**Issue by AlaaElattar** [threefoldtech/zos#2180]
- Please check the issue details here https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1889

**Comment by muhamadazmy** [comment]
According to the main issue this eventually worked fine (the one was able to reclaim the GPU) which means it can be some delay in handling the delete event or the gpu was marked as used longer than it should after the deletion.

**Comment by mariobassem** [comment]
i tried to trace the issue, here is what i found:
- the error returned to the UI here https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1889 originated in the ts client upon trying to make an rmb call `zos.gpu.list` to the node, and finding that the gpu has a contract id attached to it.
- the `zos.gpu.list` call does the following:
  - list all available gpus
  - list all active deployments
  - search for vms in these deployments, then assign the gpus attached to these vms as used by the deployment's contract.
- this means that the deployment was never deleted from the machine, although it is evident that the contract was deleted on the chain.
- consequently, this means that one of two things may have happened:
  - the contract deletion event got stuck and was never received by the node (rmb error), and the contract was only deleted when the node tried to sync its contracts with the chain (happens periodically every hour)
  - the contract deletion event was successfully received, and there was an unexpected error that occurred when trying to deprovision the node, which somehow did not happen again after a while (probably the deprovisioning happened also when syncing with the chain)

**Comment by muhamadazmy** [comment]
Just few notes:
- Events don't use rmb. the event is received by the node from the chain directly. There can be some delays but they shouldn't be lost. 
- We can see from the node logs (at this time) how the deprovision went. because according to the main issue this worked fine afterwards (how long it took from the deletion of the contract to the actual deletion of the VM)
- This issue, nor the original one included the node id to actually check the logs of the node unfortunately not even the contract number so it's hard to see if something went wrong
