### ISSUE TITLE
Errors booting new Nodes. Farm ID 2990

### ISSUE THREAD

**Issue by TullysInc** [threefoldtech/zos#2230]
- Two new nodes Dell r630s with new SSDs
- SSDs are showing in the BIOS and the farmer also reset the RAID controller, but the issues persists on reboot.

> -Scott's insight: It's not really clear what kind of issue this is. It says "file not found" but actually it's trying to reference something about networking. So that can be a "file" in the Unix sense of "everything is a file" but not actually related to storage per se

![Farm ID_2990](https://github.com/threefoldtech/zos/assets/105203696/4b015d10-08a4-4d38-af85-278be58aabf7)

**Comment by muhamadazmy** [comment]
I think the issue here is caused by `networking` not ready yet. Network can take up to 4 minutes before it's fully up. But i will investigate further because this still should wait on network before it tries to pull that one.

How long does the farmer wait on this error? Can he wait a some times (say 10min) and see if the error persists, or go away

**Comment by muhamadazmy** [comment]
I found the issue that cause this error to print. But this error should not block the node boot and should eventually go away once network is fully setup. I suggest the farmer to wait a little bit and then check if the error still showing. He needs to focus more on the errors that are coming from `networkd`. 

If the issue stayed long i suggest he makes a video of the screen for around 10min (should use some sort of a phone holder) this way we can review all logs on screen

**Comment by TullysInc** [comment]
Thanks for the detailed insight Azmy. Will inform the farmer and will update the ticket here with further information when available.
