### ISSUE TITLE
devnet zos3 nodes didn't pull the upgrade

### ISSUE THREAD

**Issue by Omarabdul3ziz** [threefoldtech/zos#2440]
## Describe the bug

zos3 nodes didn't pull the upgrade 

## To Reproduce

check the version on nodes with `zos.system.version` it is not the latest. 
also checking the logs around the update. looks it do the check but don't pull the upgrade

![image](https://github.com/user-attachments/assets/a14a0e12-8e34-484e-a8f2-2ad097a33af7)

**Comment by rawdaGastan** [comment]
The problem is found. 
1. Nodes didn't catch the update since (because we were depending on `safe_to_upgrade` flag in `zos-config` repo
- https://github.com/threefoldtech/zos/pull/2417

2. as a solution we added the flag `safe_to_upgrade` with true to be removed after all nodes catch the update
- https://github.com/threefoldtech/zos-config/pull/21

3. also dev is excluded from chain version check here 
- https://github.com/threefoldtech/zos/pull/2438

**Comment by ashraffouda** [comment]
verified - node version on devnet matched the latest commit
