### ISSUE TITLE
prepare script to migrate existing macvlans on nodes

### ISSUE THREAD

**Issue by Omarabdul3ziz** [threefoldtech/zos#2446]
prepare script to migrate existing macvlans on nodes.

since canceling zdb workload doesn't remove the instance/netns, a script is required to migrate all the wiring to use veth pairs instead of the existing macvlan

related issue: https://github.com/threefoldtech/zos/issues/2403

**Comment by Omarabdul3ziz** [comment]
### update
script is working now with myc but still fixing an issue in ygg routing rules

**Comment by Eslam-Nawara** [comment]
Verified
connected to node 11 on dev net and followed the verification steps here and now zdbs network is setup with veth pairs instead of macvlan
![image](https://github.com/user-attachments/assets/54737469-b9b4-4ef3-a91a-3e0e1e44b18d)
for node 256 (zos4 node)
![image](https://github.com/user-attachments/assets/a8b0ecfa-b18d-41eb-89b7-75dc2696a7bd)
