### ISSUE TITLE
Implement gedis client for remaining endpoints

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#266]
Gedis client has been implemented for identityd only. We still need to implement all the other BCDB endpoints:

- [x] provisiond : https://github.com/threefoldtech/zosv2/blob/master/modules/provision/remote_store.go
- [x] capacityd : https://github.com/threefoldtech/zosv2/blob/master/modules/capacity/store.go
- [x] networkd : https://github.com/threefoldtech/zosv2/blob/master/modules/network/tnodb/store.go (wait on this one since networkd is under heavy change at the moment #278 )

**Comment by muhamadazmy** [comment]
Okay, my plan was to actually use the gedis api schema to auto-generate the client, since we already can generate types from data schema. 

Unfortunately the api uses property serialization format which is harder and more time consuming to implement. hence we will instead build the API by hand, and generate the types from the jsx schema only.

We will use the schemas from there locations:
- [directory](https://github.com/threefoldtech/jumpscaleX_threebot/tree/development/ThreeBotPackages/threefold/tfgrid_directory/models)
- [workload](https://github.com/threefoldtech/jumpscaleX_threebot/tree/development/ThreeBotPackages/threefold/tfgrid_workloads/models)
- others ?

**Comment by zaibon** [comment]
> others ?

Nop, so far this is all the schemas we use.

**Comment by zaibon** [comment]
https://github.com/threefoldtech/zosv2/pull/281
