### ISSUE TITLE
decide how to expose 0-db ip/port

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#295]
Currently all 0-db are started on a different IPv6 address given by SLAAC. 
This choice has been made to avoid having to deal with port allocation and implement destination NAT.
Having a different IP by 0-DB solves all these problems. The only things to consider is to have a way to always give the same IP to the same 0-db in case of a node reboot. But this is solvable since 0-db lives on top of disk by definition so we could write that information on the disk itself or even in BCDB.

In the eventuality that we want to expose 0-DB on top of IPv4, having a different IP per 0-DB is not possible (well it is possible but very expensive). The alternative would then be to expose all the 0-DB on the same IP and start doing all the port management.
Port management is not only  a problem of which port is free when the 0-DB containers starts. But also a problem with all the masquerading happening in the DMZ. Masquerading reserve ports dynamically to allow container traffic to go out. So port will be reserved randomly without no way for 0-OS to know what is used or not. This is a hairy problem.

**Comment by delandtj** [comment]
Uhm...
for IPv6, things are simple: a 0-db it's ns gets __also__ an IPv6 address that is a `$prefixzero:$md5_of_provision_id_with_colons`, one can even tell 0-db to listen __only__ on that address with default 0-db port (deterministic). We can also on that moment disable SLAAC for these NSes, so that that __only__ have that deterministic IP.

for IPv4 , the DMZ lives in an NS, so that point is moot. a 0-db can run on the host, so you only need to manage ports, the only thing you need to pay attention to is to exclude some ports from the masquerade conntrack table (let's say 60000-65000 which would be 5K 0-db's) , but we could do the same in the public namespace or the DMZ namespace.

**Comment by zaibon** [comment]
> for IPv6, things are simple: a 0-db it's ns gets also an IPv6 address that is a $prefixzero:$md5_of_provision_id_with_colons

That would mean we assign a new IP for each reservation ? But there is only one 0-db for multiple reservation. That would lead to have a lot of IP assigned to the same interface. Isn't this a problem ?

**Comment by delandtj** [comment]
describe 'a lot'...
so a provision for a 0-db is basically a namespace in 0-db ?

**Comment by zaibon** [comment]
> 0-db is basically a namespace in 0-db ?

yes...
