### ISSUE TITLE
provisiond: need to review zdb deployment flow

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#427]
I have been testing 0-db deployment recently and I'm hitting so many issues.

- failed to deploy because not enough space while all disks are empty
- reservation never finished. like the deployment just hangs forever somewhere

The deployment flow for 0-db needs to be fully revisited.

To achieve this we need to find a way to link 3 things:
- reservation ID
- part of disks reserved for the reservation
- container ID in which the disk is mounted

There is multiple cases to handle:

1. Everything is new. The node receives a reservation for a 0-db namespace. The storage is not yet allocated on the disk. There is no 0-db container running yet.
For this case the flow is pretty straight forward:
- allocate storage on a disk
- create a 0-db container, with the disk mounted inside
- connect to the 0-db to create the namespace
- return results

2. The node or provisiond is restarted. The node receives a reservation for a 0-db namespace but the storage as already been allocated on a disk. The container can or cannot be already running.
For this case I don't have a solution. Because we need to be able to:
- find the disk on which the storage has been reserved
- check if there is a 0-db container already running for this disk or not
-depending if the container exists, check if the namespace already exists in 0-db or not.

**Comment by muhamadazmy** [comment]
I will start reviewing the zdb deployment/reservation process, and come back when I am done with (hopefully) suggestions on how to fix this

**Comment by muhamadazmy** [comment]
Okay, i did the first phase of review on the logic for provisioning a zdb namespace and came a cross a faulty process that causes the issues above.

It all starts with the in-memory zdb map (a provisiond map with (namespace ID -> container ID) ). Once the system is rebooted, (or just provisiond) the map is clean, hence on a re-provision of the same namespaces, the container is not found, hence assumed a new namespace, and a storage.Allocate is called, which increases the quota of the subvolume allocated for the zdb daemon. Do this process few times, and suddenly the allocated quota of the sub-volume is actually way more what the actual quota should be, hence the "no more free space" error.

#How to fix:
The problem is we we need to map the ns ID to a persisted location on the file-system. I suggest the following solution.

- a ZDB container is assigned a subvolume with unlimted quota (on disk)
- each new namespace creates another subvolume under the container main subvolume (the storage lib supports this while not exposed by the zbus interface)
- limit is applied to that namespace subvolume

Now, on re-provisioning of the subvolume, a quick scan of available sub-volumes will give us both the container ID (parent subvolume ID) and the namespace subvolume (mean we don't need to recreate or set any quotas), no action is taken except starting the container if not already running.

If the corresponding subvolume for the namespace ID is not found, a new one is created under the proper ZDB volume that has enough space.

@zaibon if you agree on this proposal I can start on the implementation.

**Comment by zaibon** [comment]
That seems like a reasonable approach.
So just so I'm clear here. The sub volume per namespace will be named after the reservation ID which is also the namespace name, right ? So we have a relation between reservation id, namespace name, disk used and container ID.

Regarding storage provision. What are we going to do with the sub-volume per namespace ? They are just there as information to be able to compute how much has been reserved ?

Also, the support for sub volume of volume has been removed recently because it was not used anywhere, see https://github.com/threefoldtech/zos/commit/0408e3b252203967351042b8ebb506983b96728f
I guess we would have to revert this commit then.

**Comment by muhamadazmy** [comment]
> That seems like a reasonable approach.
> So just so I'm clear here. The sub volume per namespace will be named after the reservation ID which is also the namespace name, right ? So we have a relation between reservation id, namespace name, disk used and container ID.

Yes.



> Regarding storage provision. What are we going to do with the sub-volume per namespace ? They are just there as information to be able to compute how much has been reserved ?

Actually my idea was that (since zdb create a directory for each namespace anyway) that the namespace actually contains the db and index files for the namespace. Also I checked with @maxux and it seems there is no correlation between the namespace size and the actual size of the database file. So setting a limit on the subvolume also doesn't sound like a good idea!, we instead let zdb decide the limit. (Note: this also means with current implementation, if u set the subvol limit equal to the namespace limit, the subvol limit might be reached before the namespace limit is!) 

 

> Also, the support for sub volume of volume has been removed recently because it was not used anywhere, see [0408e3b](https://github.com/threefoldtech/zos/commit/0408e3b252203967351042b8ebb506983b96728f)
> I guess we would have to revert this commit then.

I am reconsidering actually, if we are not gonna use the feature of quota for the subvolume, we still can have the same with just directories. It depends on how ZDB namespace limit works. 

@maxux ?

**Comment by maxux** [comment]
Namespace limit is `virtual current payload` limits, which doesn't take in account history, overhead of headers, etc.
It's possible to add hard-limit and get the physical size of database (by computing it, not just checking file size), and set the hard limit to not go over that limit. It's up to you :)

**Comment by zaibon** [comment]
We indeed already had issue in V1 because we were limiting the underlying storage medium with quota.
So let's avoid using quota for provisioning again.

The idea would be to instead to create a non limited sub volume for 0-db per disk.
Then leveraging the files that 0-db already creates on the filesystem to know what reservation is on which disk and how much storage is reserved.

0-db creates a directory par namespace and we use the reservation ID as namespace name. So by walking the 0-db volume we can know if a reservation is already present somewhere.
0-db also creates some metadata per namespace that we can read to know the size of the namespaces, see https://github.com/threefoldtech/0-db/blob/development/libzdb/namespace.h#L17

By combining all this I think we should have something more robust.

**Comment by zaibon** [comment]
fixed by https://github.com/threefoldtech/zos/pull/442
