### ISSUE TITLE
Design container module

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#5]
The container module is going to be responsible for exposing an interface on top of the chosen OCI runtime.

**Comment by muhamadazmy** [comment]
# Things that we need to take into consideration
- To be able to support update of the container module without the need to restart the container, containers must be `daemon-less`. This means once the container starts, the container itself is daemonized, then we should be able to connect to it directly to run commands, and receive results. 
- The container module hence can act as an access layer to the running containers, and the ability to spawn new containers, kill them, modify them while running, etc... 
- Daemon-less containers. Once a container is spawned, we should be able to directly connect to its runtime, to execute actions inside it directly, this will allow us to update the daemon without the need to restart the container.
- the container module should take care of the container network, and image (0-fs), also support modifying some container config in runtime, because as far as I have found, `runc` and other runtimes can't modify container config while running

**Comment by zaibon** [comment]
> the container module should take care of the container network, and image (0-fs), also support modifying some container config in runtime, because as far as I have found, runc and other runtimes can't modify container config while running

I kinda disagree with this. Container module is only about containers. It is basically just a wrapper around `runc` (if runc is the OCI runtime we choose)

Also modifying a container at runtime is not something we want to support. That's not how container works. If you need to have something different, you create a new container with a new config.
Having runtime configuration just makes things more complex. I want to stay as simple as possible and leverage as much from `runc` as possible. 

The layer on top will do the combination of network, container and storage to create a full container solution.

Extract from the runc documentation:
container lifecycle:
```
# run as root
cd /mycontainer
runc create mycontainerid

# view the container is created and in the "created" state
runc list

# start the process inside the container
runc start mycontainerid

# after 5 seconds view that the container has exited and is now in the stopped state
runc list

# now delete the container
runc delete mycontainerid
```
> This allows higher level systems to augment the containers creation logic with setup of various settings after the container is created and/or before it is deleted. For example, the container's network stack is commonly set up after create but before start.

This is exactly how I see things. So container module is just a wrapper thart expose a nice API for runc. Then we will use other function from other module to setup network, volumes, ...

**Comment by zaibon** [comment]
Seems runc repo already provide a Go library that allow to managed runc: https://godoc.org/github.com/opencontainers/runc/libcontainer

Need to have a closer look to it, but that could be enough for us.

**Comment by zaibon** [comment]
I started working on the design of the module: https://github.com/threefoldtech/0-OS_research/pull/17

**Comment by zaibon** [comment]
I've been reading more about OCI runtime and the specification of the [filesystem format](https://github.com/opencontainers/runtime-spec/blob/master/bundle.md).

So for runc to be able to start containers we need to provide 2 things:
1. a path to the root filesystem of the container
2. a `config.json` file that define all the properties of the container.

The point 1. is easy and already provide by the flist module.
The second point though is a bit more complex. As far as I understand this `config.json` file contains a full description of the container: process to run, limitation, kind of namespace to create, volumes to mounts...

So it seems that part of this config need to come from the flist itself: process to start, users...
Some part needs  to comes from 0-OS itself: everything related with isolation configuration, These are things we want to always enforce for security reasons.
Some part needs to come from the user when it creates the container: volumes to mounts, environment variables.

So keeping this in mind can actually shape a bit more how the interface of this module should look like. 
All the part that needs to be configurable by the user should be expose to the interface of this module. The rest needs to be hidden in the implementation

**Comment by delandtj** [comment]
with runc you can generate the config.json : `runc spec`

**Comment by zaibon** [comment]
> with runc you can generate the config.json : runc spec

yeah of course, but that all question here, is who is responsible for which part of this file.

**Comment by muhamadazmy** [comment]
@zaibon as @delandtj runc actually can generate a basic version of the config.json file that u have to fill in, we can start small and grow with time. We need to keep in mind also that we need to generate this from our container module. oci already provide the Go structure that u can fill in. which is gonna be very helpful. https://github.com/opencontainers/runtime-spec/tree/master/specs-go

Something to think about:
Currently all our containers always start `corex` as their container process. This allow us to push commands to run in containers, we still can do the same with runc of course except I am not sure how we can connect to the corex process from zos. We used to use pipes, may be corex need to have a port on the host network namespace to reach directly into it from zos host. I am not sure yet what will work with `runc`, but it would be nice to look around since you are at it.

**Comment by zaibon** [comment]
yes so I was probably not clear enough. Yes we have to generate a config.json using `runc spec`, this is a given. But then this configuration needs to be tweaked in the container module before starting any container. What I would like we agree on is what are we going to let user configure and from where?

So currently with the flist ecosystem we don't really have a way to allow flist creator to specify which process to start when using this flist. Something similar to entrypoint in Dockerfile. I know there is the .startup.toml, but I want to get away from that.

So we need to decide:
1. how we are going to solve that, and let flist creator specify these things in the flist itself.
2. What are the other part of the configuration that will be expose by the container module itself ? I think about volumes and environment variable, but there might be other...
3. What are the default configuration regarding isolation we want to enforce. This part is going to be always overwritten in the `config.json` in the container module itself.

@muhamadazmy Regarding coreX, I don't think we even need something like that anymore. runc have an exec command that let you execute command in a container already. We can do anything with that if some interaction inside the container is needed. Which mean we probably also need an `Exec` method in the container module interface.

**Comment by muhamadazmy** [comment]
Okay, i understand what u mean now.
- First, i totally agree to drop corex, a container should be more or less like docker where u define your startup command as an entrypoint
- Currently we can't attach a global meta to an flist, so it's either we provide that, or we keep a `startup` file in the flist as we do, no commitment to the current format (toml was a really bad choice)
- If we changes the flist package (it's already a tar that has the sqlite file) we can add more files where we can add a `startup` file which are limited set of the config.json, it can has the exec, the default env, exposed ports, etc and other stuff that are similar to values set by Dockefile.

Regarding the default configuration, we already currently have `privileged` and `unprivileged` profiles, that exposes different set of devices and capabilities. we can do the same with config.json and has 2 (or more) profiles ready, and just hook the extra config that we need.

**Comment by zaibon** [comment]
@muhamadazmy ok I think we're on the same page now. So it seems the real question here is really about the flist and how do we want user to build these.
I already created 2 issues about that in the 0-flist repo:
- https://github.com/threefoldtech/0-flist/issues/10
- https://github.com/threefoldtech/0-flist/issues/8

I think once we have agreed on these 2. Then we can deduct what is still to be configured in the container module interface.

I also like the idea that we provide different "profile" for our containers. That seems like a good and easy idea. I open an issue about that: https://github.com/threefoldtech/0-OS_research/issues/19

**Comment by zaibon** [comment]
I'll start already the scaffolding of the module based on the specification defined there: https://github.com/threefoldtech/zosv2/tree/flist_module/specs/container
