### ISSUE TITLE
Enable missing unit tests in CI

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#51]
Now that most of the WIP modules have been merged to master I would like we start having a proper build pipeline, CI to run as much test as possible and that we look at how we need to use go mod to version all the code.

I'm still pretty new to go mod so I don't know if what we have today is valid or not.

- [x] Enable travis-ci
- [x] Prepare tests environment for CI (some of the package are already being tested, still to activated)
  - [x] flist
  - [x] provision
  - [x] storage
  - [x] gedis
- [x] Create Makefile for building of all binaries

**Comment by zaibon** [comment]
I moved all the binaries into `cmds` directory at the root of the repository.
Each binary folder have its own go.mod files. So they can live their own live.
I added a replace statement for the `github.com/threefoldtech/zosv2/modules` module so until we have a release we use the local file in the repository as source. 

Everything seems to build fine with this setup

**Comment by muhamadazmy** [comment]
@zaibon 

The current code tree makes the `modules` directory a single modules. which means ALL implementation logic for all the modules has the same version. 

Even after binary separation to the `cmds` directory, it still fully depend on the moduels module which has the implementation. This also makes it very hard to work on separate moduels (network for example) because u have to push before u can build the binary otherwise the `go build` will only use the cached version of `modules`

If we need to have a separate `independent` modules with separate versions each implementation (and it's binary) has to be a separate go module so it can have independent versioning and can be developed and tested without the need to push every separate change.

I need your approval to this change before I restructure the code tree.

**Comment by zaibon** [comment]
>  which means ALL implementation logic for all the modules has the same version.

Indeed this is the case for now.

> This also makes it very hard to work on separate modules (network for example) because u have to push before u can build the binary otherwise the go build will only use the cached version of modules

This is solve already, I added some replace directory in the go.mod file, so you can use the local file for the zosv2 modules

> If we need to have a separate independent

I think at some point we will want to have a different version for each module. I don't think we need to do this right now though since there is nothing released yet.
Now this means we'll most probably need to have a separate repository per zos module. And most probably one or more common module that other module share.

> I need your approval to this change before I restructure the code tree.

Let's not change anything for now, we're still too early in the development to make these change. But just to know, how exactly were you planning to change the structure ?

**Comment by muhamadazmy** [comment]
Draft for the make file
https://github.com/threefoldtech/zosv2/pull/68/files

**Comment by zaibon** [comment]
https://github.com/threefoldtech/zosv2/pull/68 merged

**Comment by zaibon** [comment]
I increased the priority of this one since we start to have a code base with quite some code and I've seen some tests and linting errors slipping in.

**Comment by zaibon** [comment]
I've open a draft PR https://github.com/threefoldtech/zosv2/pull/186 that enables all the tests I could find that can just run as they are today.

There some modules that requires more work for the test to pass though.

**Comment by zaibon** [comment]
#186 have been merged. But some test for certain package are still skipped.
I'll update the first comment to list all the package that still need to be enabled

**Comment by muhamadazmy** [comment]
I am not sure if there is still anything to do related to this issue, @zaibon ?

**Comment by zaibon** [comment]
yes there is. All the uncheck box in the first comment are still to be done.
