### ISSUE TITLE
k8s cluster: cannot deploy 2 VM on the same node using the same network

### ISSUE THREAD

**Issue by BolaNasr** [threefoldtech/zos#585]
Reservation_id : 1276350
![image](https://user-images.githubusercontent.com/10259267/76944664-17511280-690a-11ea-859c-bd5d3cd176c7.png)
we need to know how they choose interface name in zos ?

because this problem depend on this 
![photo_2020-03-18_11-22-32](https://user-images.githubusercontent.com/10259267/76945140-cee62480-690a-11ea-979d-4de968b35f60.jpg)

**Comment by grimpy** [comment]
Happened again today see: http://explorer.testnet.grid.tf/explorer/reservations/459470

**Comment by LeeSmet** [comment]
> Happened again today see: http://explorer.testnet.grid.tf/explorer/reservations/459470

This reservation tries to deploy 2 times 2 vms on a single node, which is not supported. The name of the tap device is fixed for a network, so indeed this causes a naming collision. This can be observed by checking the results of the workloads. The lower numbered workloads get deployed first, and succeed, the higher number onces fail because a vm and tap is already present on the node in that network.

**Comment by zaibon** [comment]
We should detect when trying to deploy 2 VM on the same network and same node and return a proper error message explaining the problem instead of the weird TAP error.

Documentation must also be updated to explain the limitations.

**Comment by DylanVerstraete** [comment]
Closed in https://github.com/threefoldtech/zos/commit/dc056a7b3558c5f9302ff298ab204f136e87907d
