### ISSUE TITLE
explorer: avoid generating currency account on behalf of users

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#666]
At the moment, when a reservation is registered on the explorer. A "token account" is generated for each `user-farmer` pair. Then a payment invitation is generated which contain all the generated `user-farmer` and the amount to pay for each farmer.

This solution works great and make transaction tracking super easy in the explorer.
It has some flaws though:
- explorer have to store seed used to generate user-farmer account
- the user have to create multiple transaction to fulfill a same reservation

Here is an alternative proposal to address these flaws.
In this model the way we manage user and farmer account is the same so i will just refer to it as user account.

Instead of creating a account for each `user-farmer` pair, only one address per currency and user is stored. 
This account is NOT created by the explorer itself, but "given" from the user. To achieve this, the user would generate a new account (so he is the one owning the seed for it).
It configure the account with the multisig options to allow the explorer to create transaction to/from this account.
The user then tell to the explorer the address of this multisig account.

At this point we assume both farmers and users have their account registered on the explorer and the explorer can create transactions with them(the accounts). The user account are also founded with some tokens.

The reservation flow is the following:
- user register a reservation and specify in which currency he wants to pay for it
- explorer checks the farmer listed in the reservation accept this currency
  - if no,mark reservation invalid, return an error to the user => the end
- explorer check the user account for the chosen currency is founded enough to pay the total amount of the reservation
  - if no, mark reservation invalid, return an error to the user => the end
- explorer set the reservation status to `deploy`
- nodes provision each workloads
  - at least one of the workload fails to provision, mark reservation invalid => the end
- all workloads are deployed, explorer creates all the required transaction to pay all the farmers involved in the reservation
  - if one of the transaction fails for any reason ( in the mean time no more fund in the user account for example), explorer cancel reservation, refund user => the end
- everything is done. happy ending.

**Comment by LeeSmet** [comment]
> the user have to create multiple transaction to fulfill a same reservation

This is not true, you can send funds to multiple receivers in the same transaction, just like you can now in tfchain. Regardless I don't see why this would be a problem, as we aim to have tooling around this anyway so the user does not need to do this manually.

> explorer have to store seed used to generate user-farmer account

While it is true that this is a liability, I think we can solve this with encryption of the keypair based on the private key of the seed used to start the explorer. In this scenario, if someone where to compromise the database to steal the funds, they would also need to have the seed. So unless they have that there is no real harm. If they do have that, they could steal money from escrows: this equates to all money in the escrows for reservations which have not yet been successfully deployed, and have at least a bit of funding. So in the regular flow that would not be a lot. But in this scenario with the new plan, the attacker could steal all money from all accounts used to pay for reservations. Which would be waaay more since the idea is that the users just pay this account once every month or so to last a whole month. Also, in case of compromise, in the current design WE can create new escrow accounts: just delete the existing accounts in the db. A new escrow is then generated on the next reservation. We return the escrow address anyway, so there should be no harm here. In the new design, we would require a user to set up a whole new account to do reservations with, which will be more of a hassle and for sure some users will just ignore it.

It also seems this design adds 2 more failure conditions whilst not removing any existing ones:

- The user now needs to have enough funds up front.
- It's possible there are no longer enough funds when a reservation is provisioned.

But probably the biggest issue I have is that the user now would need to manage this new account. So a user needs to manage 2 accounts. How is he going to do this? i.e. is there tooling like the 3bot connect app to support this? Furthermore the user needs to set up this account. And I guess the public key of the explorer can change, so we'll need some way to expose this. And we are allowed to take funds from this account whenever we want. So the user now needs to implicitly trust us to not abuse this. If he does not, he'll have to make a transaction to this wallet every time he wants to make a reservation. And even then, because we check if the user has enough funds when a reservation arrives and bail if this is not the case, there is a window where we can steal his funds. So this will definitely lead to us getting blamed for a user who misplaced some of his tokens. To make matters worse, this is a full blown account, so there will surely be users who will use this account as their main account, meaning we would have a backdoor into their wallet.

Furthermore, the usability of the special account is tied to the seed of the explorer, meaning we can't freely switch that out even if we wanted to, which we could now.

I will also assume that we still use the explorer seed to fund the transactions, so nothing changes there.

Overall, it feels like we are going to add overhead to the user to manage this new account, which leads to worse UX, while we always stated it should be as easy as possible for the user, and we don't really gain anything from it. In fact, we open ourselves up to a load of blame when something goes wrong on anything that comes near these accounts. 

If we want added security for the existing escrows, we could encrypt the keypair. This ties the escrows to the seed of the explorer (as this design would). Or, we could take that idea from this design, and setup the escrow addresses with a multisig where the explorer pubkey can sign on its own as well, and then throw away the key. This also ties the escrow to the used explorer seed. Both work I suppose, and this ("this" being the second option) would mean we save slightly less data in the db (we only need the address now).

**Comment by zaibon** [comment]
> This is not true, you can send funds to multiple receivers in the same transaction, just like you can now in tfchain

Good to know. This mean the assumption made first were wrong.

Reading the other remark you made it appears this proposal only actually bring one thing. The fact that a user can fund an account once and do reserve capacity for a while without the need to actually do new transactions. While this bring a little bit of UX improvement this can also be easily achieve with proper tooling around. And on the other hand we open up our-self to a lot more danger and eventual catastrophe since the potential amount of token the explorer can access will be huge.

> If we want added security for the existing escrows, we could encrypt the keypair.

This is mandatory for sure. I'll open another issue to already implement that part. (https://github.com/threefoldtech/zos/issues/669)

**Comment by LeeSmet** [comment]
Ineed, this would be a marginal improvement in UX for the reservation, but also adds the overhead that the user needs to add his account to the reservation. Not a problem with proper tooling, but then again, that won't be a problem in the current flow either, especially given that we would use qr codes and such. Also we bring in the overhead of actually funding this account, which is harder to provide tooling for.

While we are on the subject of UX, I'd also like to point out that the current escrow design can simply be removed once we have threebot. Instead of doing all the stuff with escrow addresses, we just return the farmer addresses. That means all escrow related code can go away, and we need 0 change in the api. So all tooling continues to work on the client side. Ofcource the farmer end will need 3bot to actually sign then. but other than that the change would be isolated to the explorer. In this design, that would change, unless we keep the explorer as a man in the middle to manage the actual payment, but imo if we can cut that out, we should. The less code there is the less bugs there can be

**Comment by zaibon** [comment]
There always will be the need for a middle man in the payment process as far as I now to ensure the foundation fee and burning are executed (when new tokenonomics are in place) unless there are way to define such a thing on stellar?

**Comment by zaibon** [comment]
After sleeping on it, this is what is comes down to.
The proposal is not good enough and we have highlighted too many security issues with it.
The current design is way more secure so we will stick with it. 
This exercise did showed something though, UX wise we want to be able for the user to pay a reservation by doing one single action.

In a perfect world, wallets would allow to scan a QR code that creates a transaction to pay all the farmers. But reality is different and most wallet just allow creation of transaction 1 to 1.

So to solve this we need to take another approach. Instead of creating an address per `user-farmer` pair. There will be a single address per user. The explorer will then be responsible to split the total amount between farmers.
This solution keeps all the same security properties the current solution has and also allow better UX for the user.
