### ISSUE TITLE
explorer: change the way addresses are generated for reservation payment.

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#674]
Follow up from https://github.com/threefoldtech/zos/issues/666

> In a perfect world, wallets would allow to scan a QR code that creates a transaction to pay all the farmers. But reality is different and most wallet just allow creation of transaction 1 to 1.

So to solve this we need to take another approach. Instead of creating an address per user-farmer pair. There will be a single address per user. The explorer will then be responsible to split the total amount between farmers.
This solution keeps all the same security properties the current solution has and also allow better UX for the user.

**Comment by LeeSmet** [comment]
I have just 1 remark: The old/current design allows for different currencies to be used per farmer, meaning you could create a reservation with 3 farmers, which each accept a different currency, and as long as the user has these currencies, he can simply the different escrows in the right currency and the reservation will still pass. Now this will no longer be the case, as there will need to be 1 global currency for the reservation. I'm not sure how much of a problem this will be, if any, but it might seriously limit the usability of FreeTFT, since I don't think many farmers will accept that.

On a technical level, this means that splitting the funds will need to be done by us, instead of the user, and we would create an escrow address for every user, not for every user-farmer pair.

 The api interface change required is as such:

- when a client creates a reservation, he now needs to receive 1 escrow address, and the total amount he needs to pay. 

Question here: do we want to just return a single address and amount, or do we want to keep the list of amounts per farmer ID, and a single address. The later scenario would allow for a detailed overview of which farmer gets paid how much, but requires the total funds to be calculated client side (by adding the individual amounts).

Even though the root cause of this issue is the payment tooling which will likely not be ready for the launch deadline, we should still have tooling to simply create the reservation, which can handle this (the second case), and print the total payment for the user (please correct me if I'm wrong).

Internally:

- the EscrowInfo will need to be changed to match the second scenario described above, so the address is removed here. Now the address is stored on the escrow object attached to the reservation. This way, we keep track of which farmer needs to receive how much. To track the reservation payment status, we simply add together the amounts, and check if the funds for the reservation on the escrow are at least this amount. The current way of paying an escrow can stay in place for this. Also the current flow of refunding an escrow (which simply sends all funds for a reservation to the first funder), can also stay in place.

- A slight modification will be needed to the payout farmer method. Rather than taking money from an escrow and sending it to the farmer, we will now create 1 transaction which takes all required funds from the single escrow, and splits them over the farmers, as described in the escrowinfo. 
  - we can either have 1 payment operation for the foundation, which collects all the funds going to the reservation
  - or we have a payment operation for every farmer payout, so we can more easily see how much funds the foundation got from each farmer, should we want. We can easily calculate this anyway, so this is probably not required

- An escrow account will be tied to the customer_tid, not to the pair of customer_tid farmer_tid. Meaning we will need a slight structure change to how this is tracked

**Comment by zaibon** [comment]
> Now this will no longer be the case, as there will need to be 1 global currency for the reservation. I'm not sure how much of a problem this will be, if any, but it might seriously limit the usability of FreeTFT, since I don't think many farmers will accept that.

This is right. One single currency per reservation. Regarding FreeTFT refer to https://github.com/threefoldtech/zos/issues/667 for more details.
