### ISSUE TITLE
Design metric/monitoring module

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#7]

**Comment by muhamadazmy** [comment]
I think we also need to have a visual statistics UI for machines owners to have a quick overview of the machine health and load (similar to the boot screen of V1). Currently with V2 (specially since we have no logs on screen anymore) there is noway to see if the machine is doing well or not, or if it got IP in the local network

**Comment by zaibon** [comment]
@muhamadazmy yep right. I don't have anything against re-using the same kind of boot screen we had in the v1. Let's just define what we want to show on it and move the code in this repo. ~~I'll open an issue for it.~~ issue opened: https://github.com/threefoldtech/zosv2/issues/197

**Comment by muhamadazmy** [comment]
# Metrics
## System
- CPU percentage
- CPU Load/Avg
- Swap (we don't have this in zos)
- Temperature 
- Disk usage
- Disk IO
- Memory Usage (Used/Free)
- Network TX/RX per interface
## Host
- Node ID
- Farmer ID
- Version
- Up time
- Public IPs
## Provision
- Number of containers
- Number of volumes
- Number of ZDB namespaces
- Number of  Networks ?


The monitoring module should use zbus events to publish the monitoring statics (on different channels) for other parts of the system to subscribe. 

A UI for example can just subscribe to the event stream, and then render the data on screen.
