### ISSUE TITLE
provisiond: some nodes report very little reserved storage unit but have disk fully allocated

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#704]
proposed solution: #709

**Comment by muhamadazmy** [comment]
I think this related to storaged, not provisiond

**Comment by muhamadazmy** [comment]
I was checking the code regarding the reported capacity and:
- I can't seem to spot where exactly we report back 'realtime (or even eventual)'  capacity consumption back to the explorer. capacityd only report the capacity one time on registration.  
- It also seems that provisiond does not really report this back as well when deploying new reservation
(I am wondering if i missed something)
- But if that is the case, may be a better approach to this problem is that each daemon can report the amount of resources it thinks consumed (as metrics) then capacityd can aggregate this information and make sure it's reported back to the explorer periodically

**Comment by DylanVerstraete** [comment]
@zaibon what is the status of this? Did we fix this in https://github.com/threefoldtech/zos/issues/709?

**Comment by zaibon** [comment]
yes indeed, I think all the work regarding #709 should have fix this issue too. I'll close it
