### ISSUE TITLE
Escrow details returned from reservation register are empty

### ISSUE THREAD

**Issue by ranatrk** [threefoldtech/zos#744]
When creating a new reservation and registering it through jumpscale, the escrow object returned doesn't include the details(farmer_ids and the amount to be payed). Only the asset and address are returned.
- explorer: **explorer.devnet.grid.tf**
- reservation_id :**73** (and previously 72 also)
- results: **OK**
- escrow results: 
![Screenshot from 2020-04-21 17-45-00](https://user-images.githubusercontent.com/17128393/79885789-db710780-83f7-11ea-886f-5d29cde42eb2.png)

**Comment by zaibon** [comment]
I think this can happen when the reservation ends up free of charge. This can happens when, like now, the reservation only contains a network workload. At the moment the networks are free. So there is payment details list is empty cause there is nothing to pay.

What should have happened is your reservation `next_action` value should automatically switch to `deploy` without blocking on the `pay` state.

**Comment by ranatrk** [comment]
Indeed that is the case, I tried with another reservation that was of a different type (container workload) and the details were returned. Thank you
