### ISSUE TITLE
Resource IDs and ownership of resources

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/zos#83]
Reservation can (and will) happen on multiple steps. For example to start a container you probably have to do the following:

- Create a storage volume
- Allocate network resource
- Create container, and assign both the volume, and the network resource to that container. 

The problem is, on creating a container you need to pass the the information of the volume (may be the volume full path) and the network resource identity as well. But there is no way to grantee that the caller of the container creation is the rightful owner of the associated resources (volume and/or network)

We think that the IDs of the allocated resources should carry some information about the owner of the resource. so in that case, if the id of the volume and the network matches the owner of the container, the container creation should pass.

### Proposal 
an id of a resource can be a jwt token with payload that contains both the resource information needed, plus the tenant id. The jwt token is signed with the node private key so the jwt is only valid on the node where the resource is allocated. 

Example, you first allocate a volume, the volume id can hold the 

```json
{
  "path": "/pool/volume",
  "tenant": "id of the owner"
}
```
then on container creation, the jwt token is passed as the volume id. the node can then verify that the `jwt` has valid signature, then matches the tenant id to the tenant id of the container.create caller. Once verified, the volume path can be mounted inside the container.

The only drawback for using this technique is the size of the `jwt` token.

**Comment by delandtj** [comment]
'drawback' ... a mountpoint that big with godknows what characters in there is a big nono

**Comment by delandtj** [comment]
maybe an md5 hash of that token as mountpoint ? (and then even the 1st 8 bytes ?(or the last?))

**Comment by LeeSmet** [comment]
@delandtj if it's a JWT, the characters are the base64url encoding set (`a-zA-Z0-9_-`)

**Comment by muhamadazmy** [comment]
@delandtj you didn't fully understand me 

The mount point is NOT the jwt. the JWT holds the mountpoint in the data payload this can be something like `/mnt/pools/pool1/subvol1` (the path in the payload above) and the tenant id
Then we make a signed jwt with this content. this jwt identifies the subvolume. Now when u want to mount this subvolume in a container. We just pass the jwt as the id of the subvol to mount, then the node will verify the jwt, and then uses the pass encoded in the body.

**Comment by delandtj** [comment]
I stand corrected

**Comment by zaibon** [comment]
The problem raised by @muhamadazmy is indeed something we need to solve.
But his proposal cannot be implement as it is. Reason is, his proposal assumes the ID of a reserved volumes is generated by a node and then somehow sent back to the user that requests it.

This is actually not how things works. A reservation schema is something that is fully generated client side. Then it will be written on the bcdb and the node will eventually get the reservation schema and deploy the requests workloads. And the story ends there. As of today there is no way for a node to communicate with anything else then the bcdb itself. So the generation of a JWT used as ID of the workload is not possible.

But the concept is correct. We need a way to attach the user ID to the reservation schema.
Maybe all the reservation schema should include a signature and a user ID field.
So we could at any point in time check that the content of a reservation is unchanged and from who it came from.

**Comment by zaibon** [comment]
I think I have a way to solve our problems. 
A reservation object already contains the identity of the creator of the reservation.
If we add a signature to reservation object we obtain 2 things
1. we make sure the reservation has not been modified on the way to the node
2. we can verify who is the author of the reservation, aka the owner of the capacity the node will provide.

If we use this signature to create the IDs of all the ressources (volumes, container, ...)
Then we can always map a user to a reservation and to a resource.
Checking if a user can use a certain resource becomes as trivial as keeping a map of the resource ID and the user ID.
This mapping doesn't even have to be kept on the node, this is fully stateless since it everying can be rebuilt from the
original reservation object (which is immutable and always available in the bcdb)

In order to avoid doing too many round trips to the bcdb, we can keep a certain amount of resource and user ID mapping in memory
in a LRU cache or something. Then in the case we receive a reservation that reference another reservation that we don't have 
in memory we can fetch it from the bcdb. Once we have it we can verify its signature, re-generate the resource id and make sure
the reservation we are processing doesn't try to access some resource from another user.

I've already implemented a POC of all the cryptography required to do this. This all works good.

Some open questions: 
- what kind of hash to use ? we need something that can be used in a path since the ID of a volume is its mountpoint
- do we create the hash from the reservation content or from the signature itself ?

**Comment by maxux** [comment]
That sound great !

1. I think `sha256` is a quite good for that
2. Why not both ? A mix of everything, since data are immuable.

**Comment by zaibon** [comment]
> I think sha256 is a quite good for that

Good, I think too. That's what I used in my draft PR : https://github.com/threefoldtech/zosv2/pull/143

> Why not both ? A mix of everything, since data are immuable.

Well I was thinking since the signature is already a hash of the reservation content maybe that would just be double work. We could perfectly just hash the signature itself to bring it to a reasonable size.
