### ISSUE TITLE
HDD disks should only be used by 0-DB

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#832]
To make sure we get best performance how of HDD, only one 0-DB should be able to access it.

This means volume and container root filesystem can only be deployed on SSD.

Todo:
- [x] provisiond refuse to create a volume or a container root filesytem subvolume on HDD
- [x] explorer should return an error if a reservation with a volume on HDD is received
- [x] chat flow should not propose HDD for root filesystem or volume anymore (also no SSD option for ZDB)
  - [x] Volume/Container should always be SSD
  - [x] ZDB should always be HDD
- ~~zdb should only support HDD namespace type (disable the option to select SSD)~~

**Comment by muhamadazmy** [comment]
I think this should be fixed at the `storage daemon` level. Currently the storaged does not differentiate  between an HDD and SDD, both are available for subvolume allocation. This of course complicate the calculation for the reserved volume size since we have to treat the subvolume for containers differently from the ones we allocate to ZDBs. 

If we gonna make SSDs only available for workloads (container rootfs, or data volumes) and use ALL HDDs (and only HDDs) for ZDBs, this will simplify the implementation a lot. So separation must be implemented at the stroaged level.

> While implementing this is super easy, the problem we have right now is the backward comparability with existing data volumes that were assigned to HDD type!

Proposal:
- Storage daemon should keep track of 2 set of pools SSD and HDD separately 
- Only subvolume allocation is done over SSD
- For ZDB namespace allocation, all "active" disks are searched for enough "space" to fit this namespace. ZDB metadata is checked to make sure namespace reservation would fit, otherwise try another disk.
- If no active disk is made a new disk is mounted (from the pool) and the namespace data is written, provision continues (spawn the zdb container if needed) 
- I would prefer having different mountpoints for the disks (group them differently) but this would be bad if we want to maintain backward compatibility 

Proposal 2:
While this is easier to implement,it's not gonna produce "nice" code. is to basically do validation on the data make sure that only ssd type is required for flists, and hdd is for all zdbs. It's way less work but we keep a lot of code logic that does not make sense anymore. the plus side to this is that we can revert back to current implementation way more easier.

**Comment by zaibon** [comment]
I would prefer proposal 2. My reasoning is I prefer have more capable storage daemon and we just limit what it does, then changing all the code to remove the capabilities altogether. Let's plan for the future. Backward compatibility is the second reason, we need to let all the volume and root filesystem deployed today on SSD expires over time.

**Comment by rkhamis** [comment]
added to jumpscale 10.7 for this:

> chat flow should not propose HDD for root filesystem or volume anymore (also no SSD option for ZDB)
>  - Volume/Container should always be SSD 
> -  ZDB should always be HDD

**Comment by BolaNasr** [comment]
Fixed Chatflows: (https://github.com/threefoldtech/jumpscaleX_threebot/commit/50cdfc7bd1ccd5661eb14de8ea514c1c9b32dcad) 
- Volume/Container should always be SSD
- ZDB should always be HDD
