### ISSUE TITLE
Shutdown disks after boot

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/zos#856]
We want to shutdown disks after boot in order to save power.

**Comment by DylanVerstraete** [comment]
There is a cli utility called `hdparm` which can manage everything around physical disks. There is also a go implementation of it: 
https://github.com/adelolmo/hd-idle

We have multiple problems though:
  - every disk behind HBA don't expose SCGI/SG commands.
  - SCSI disks can't be shutdown without putting custom logic around it to power them back on and mount them before use.

We kinda made a design flaw here, the whole storage backend is built on permanent available disks..

**Comment by zaibon** [comment]
> We kinda made a design flaw here, the whole storage backend is built on permanent available disks..

Why do mean exactly by this ? Disk can only be shutdown when there are not used. So there are no active reservation using it. As soon as one bytes of the disk is reserved, the disk cannot be shutdown anymore.
So the goal here is to try to keep the power consumption of big storage server with lot of disk to a minimum until all the disk are actually use, in which case the power consumed is not wasted anymore since it's actually serving data.

> every disk behind HBA don't expose SCGI/SG commands.

Not much we can do about it I'm afraid

> SCSI disks can't be shutdown without putting custom logic around it to power them back on and mount them before use.

Which is doable IMO

**Comment by delandtj** [comment]
Design flaw:
All disks are pre-formated (that's OK), but effectively mounted. We shouldn't do that, as in proper SCSI terms, spinning down a disk with an INQUIRY command over SG, effectively makes it unavailable for the OS until it's spinned up again (That is not the case for SATA disks that have inherited IDE semantics for workstations, where these disks can get a timer to go to sleep when not accessed during some time, and automatically spin up when there is access)
I would opt for a proper setup where the disks that do not have some reservation are not mounted either. So the behavior of `storaged` needs revisiting if we want to go that path. 
I think it's necessary to handle disks all the same way, so that there is no difference between SATA disks and real SAS (scsi) disks, so that only disks that need to be mounted are spun up when necesary

**Comment by delandtj** [comment]
so https://github.com/adelolmo/hd-idle is just one part, the moment a disk is behind a HBA, things get a lot more hairy, where each kind has some tool (mostly binaries and closed-source) to configure VD, spin up/down disks (if at all), and these tools then need to be incorporated in zos(directly or through flists) so that we can handle the disks.
The more, these tools and the OS have different views of disk numbering, so we'll need to learn behavior of which is which.

Most controllers I have seen in the field (if not all) are Broadcom/LSI HBA's (AVAGO) that can be controlled with `storcli`.
That tool needs to be incorporated too , as disks behind a HBA mostly won't get output from `smartmon` tools either.

Yeah, storage is still a big hairy blob that hasn't been tackled yet, IMHO

**Comment by zaibon** [comment]
> So the behavior of storaged needs revisiting if we want to go that path.

I wouldn't call that a design flaw. The current code was simply not design to behave that way. And yes storaged needs to be adapted but isn't this the all point of this issue ? :-D

**Comment by LeeSmet** [comment]
the current storage module is very minimal afaik. The reason disks are mounted at boot, is just because there is a line of code which mounts all volumes it find at boot. So its easy to change this behavior if needed. Given the idea that disks may or may not be down, which might be managed by some utiltiy, this might be a good opportunity to add some proper code design in the storage module in general, with some decent abstractions

**Comment by DylanVerstraete** [comment]
We could rewrite the storage module to do following:

On startup:

- Only mount volumes which are activly in use by reservations (disable disk spinoff, since this will cause the hard drive harm in the long run)
- The volumes that contain no active reservations we can unmount and spinoff the disks.

If a reservation comes in and there is no space left on a mounted volume, we check if there are other disks that can hold this reservation. If a disk is suitable, we mount a volume and again disable the disk spinoff.

This way only used disks will keep running and the one we don't use / need will be turned off.

**Comment by zaibon** [comment]
That sounds reasonable. Keep also in mind that at boot capacity needs to have a complete view on all the disk to report the total capacity of the node. After this the unused disk can be shutdown.

We might also need to change the logic used to select disk. I think at the moment we filter all the disk with enough capacity, then sort it by free space in descending order, and pick the first one. This algo is not optimal is we want to keep as much disk unused as possible. (https://github.com/threefoldtech/zos/blob/31ead5f3a3f3e7d12bbf98b261ab74ac974f9ec1/pkg/storage/storage.go#L442:25)
