### ISSUE TITLE
Creating a volume in 1 reservation and attaching it in another doesnt work

### ISSUE THREAD

**Issue by MathiasDeWeerdt** [threefoldtech/zos#860]
I created 2 volumes in one reservation and paid for them, then I created a few containers and attached the storage to them in another reservation but that doesnt seem to work.

Note: If I do the volume creation and container creation in the same reservation, then it does work.

Volumes are registered in ID: 10194
Containers are registered in ID: 10195

Error:
![image](https://user-images.githubusercontent.com/7256303/86471863-6d718680-bd3e-11ea-8c96-c741b5f1668b.png)

**Comment by zaibon** [comment]
I've looked at [10195](https://explorer.grid.tf/explorer/reservations/10195) and the way you attach the volume to the container is not correct.
```json
"volumes": [{"volume_id": "-2", "mountpoint": "/etc/letsencrypt/live/freeflowconnect.tfgw-prod-05.gateway.tf/"}]
```
The problems from from the `"volume_id": "-2"` which should be `10194-2` since you reference a volume that is already created.
When you use `-2` you say, mount the volume that is created in this same reservation with the workload ID 2.

If you use the JSX SAL, replace you call to the [zos.volume.attach](https://github.com/threefoldtech/jumpscaleX_libs/blob/development/JumpscaleLibs/sal/zosv2/volumes.py#L32) to [zos.volume.attach_existing](https://github.com/threefoldtech/jumpscaleX_libs/blob/development/JumpscaleLibs/sal/zosv2/volumes.py#L46)
