### ISSUE TITLE
flistd should watch the 0-fs processes and cleanup after they stops

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#864]
At the moment, flistd just fires the 0-fs process in daemon mode and forgets about it.
This is a problem when a 0-fs crashes and leave the mountpoint dirty. flistd should watch the 0-fs processes and clean up behind it if needed.

**Comment by muhamadazmy** [comment]
This one is tricky due to the following reasons.
- We can't just leave the 0-fs processes attached (as children) to flistd, otherwise they will also die if flistd crashes or exits due to an update
- We can then instead keep a state somewhere on the system where flistd tries to use to make sure those "states" are actually running, in case the process associated with this state is gone, a clean up is applied. The problem with this is that it's a "poll" operation, so we need to keep polling for running 0-fs processes to make sure they are still running.
- The 3rd solution is that we can have a small wrapper that starts the 0-fs process, waits for it until it exits then, once it exits it runs a clean up binary or script.
-  The last solution, is we can start 0-fs as a zinit unit.  The problem is currently zinit does not support an `on-exit` executable in it's configuration, but we won't have an extra process per each 0-fs process as previous solution.

The fastest/easiest solution is having a wrapper process that runs and waits for 0-fs to exit and then run a clean up script. This tool can be generic so it can be used for other stuff as well (can't think of use cases)

@zaibon what do u think?

**Comment by zaibon** [comment]
> We can't just leave the 0-fs processes attached (as children) to flistd, otherwise they will also die if flistd crashes or exits due to an update

right, which was why we start it as a daemon in the first place.

> We can then instead keep a state somewhere on the system where flistd tries to use to make sure those "states" are actually running, in case the process associated with this state is gone, a clean up is applied

This is interesting solution. Keeping a list of running 0-fs shouldn't be hard at all. 0-fs when started in daemon mode already writes its pid in a directory, so flistd could keep track of what flist is running under which pid. Watch a state change for any 0fs process and act accordingly. 

> The 3rd solution is that we can have a small wrapper that starts the 0-fs process, waits for it until it exits then, once it exits it runs a clean up binary or script.

This could be an idea, but that will not allow to restart the 0fs process if that would be required. So having this logic managed by flistd allow to have more option regarding how to handle the 0-fs process dying.

> The last solution, is we can start 0-fs as a zinit unit. 

I also think this is not the right way to go. 0fs process are just utility of flistd, so flistd should be master here I believe

**Comment by muhamadazmy** [comment]
@zaibon restarting 0-fs on failure is never possible, because once the fuse process dies, the mount point is completely invalidated and all IO operation will return an error that the trasport endpoint is not connected. Restarting the process will not fix it, because that would be in a completely different mount namespace. Hence container is completely dead. The only way is to recreate the container from scratch.

Anyway, this issue is regarding clean up, not container recovery, so we should focus on the solution to cleanup the crashed filesystem.

**Comment by zaibon** [comment]
> The only way is to recreate the container from scratch.

But isn't it what is going to happen anyhow ? Because if the process in the container receives an IO error, it will crash. Then containerd will restart the container automatically with the exact same config. So if 0-fs is also restarted, the container will also be able to restart fine, no ?

**Comment by muhamadazmy** [comment]
@zaibon Well, it's a good point but we can't be sure. does it only restart the failed task (process) or does it recreate all the namespaces from scratch? Also other questions
- We are not sure that the container entrypoint will crash if it receive an IO error. It's not like a sigfault, or a kill 9, that's an error that the process can completely choose to ignore.
- The scenario u suggest is a bit racy, we don't know what will restart first.
