### ISSUE TITLE
Btrfs subvolumes are not cleaned up

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/zos#879]
Since we want to add the disk shutdown feature we need to make sure there are no subvolumes on a disk before shutting it down. But right now we cannot do that because some subvolumes are never cleaned up.

For example if you reserve a zdb it creates a subvolumes on a disk, but when this reservation is expired or canceled this subvolumes is never deleted. Hence we can't shutdown the disk if it was the only subvolume on there..

For volume reservations it works fine, subvolumes are cleaned up after they are expired or canceled. I wonder if we can do the same for zdb's.

Also we need to find a way to clean up existing subvolumes on existing nodes..

**Comment by DylanVerstraete** [comment]
It has 77 subvolumes on 1 of the disks.
![Screenshot from 2020-08-04 11-28-07](https://user-images.githubusercontent.com/17138347/89277851-a5256400-d645-11ea-83f1-a65321a21d0d.png)
But in the explorer nothing is currently active.
![Screenshot from 2020-08-04 11-28-19](https://user-images.githubusercontent.com/17138347/89277864-a8205480-d645-11ea-8caa-55cca7354f39.png)

**Comment by zaibon** [comment]
Regarding 0-DB, we could indeed also remove the subvolume used by the container but only when there are no more 0-db namespace reservation active on the node. Reason is 0-db container uses a single subvolume, but on this subvolume, multiple reservation lives. Other then this, I think we can safely implement that indeed.

Regarding the leftover subvolume, I think this is what is also addresses in this issue: https://github.com/threefoldtech/zos/issues/709 and it seems we should start looking into this a bit more seriously since we seem to leak quite a lot of storage now.
