### ISSUE TITLE
postscript or helm support for k8s solution

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/zos#888]
Problem: We want to provide a solution based on k8s in the marketplace/admin dashboard [zeroCI](https://github.com/threefoldtech/zeroCI/blob/development/docs/installation.md). The installation steps are 
1.  provision k8s
2. solution expose
3. ssh into the master
4. configure domain
5. k8s apply

Right now, steps 3 - 5 are not automated, first if using the marketplace we can use these wg config (the user probably is already connected to it), and we can't ask them for access either. 

Suggestions:

# use a deployer container as part of the reservation
add another container to the reservation, and from there we execute commands against the master on the network to invoke the installation script

# having a postscript could be added as a feature in the k8s
allowing having a specific script to run against the master node once the machine is rebooted for the first time?

# rancher + helm

as stated in https://rancher.com/docs/k3s/latest/en/helm/ 
```
Any file found in /var/lib/rancher/k3s/server/manifests will automatically be deployed to Kubernetes in a manner similar to kubectl apply.
```
I think that might be the best solution, also would open up the space of helm packages automation too on the grid

**Comment by zaibon** [comment]
Hum actually I'm not sure we want to go that direction. The k8s primitive how it is design at the moment is just to allow to deploy a k8s cluster. What you do with your cluster is 100% in the hand of the user. 0-OS doesn't have access inside the user workload and I think it should not.

From what I understand your issue is due to the fact that you are a service provide deploying workload on behalf of the user and thus are not supposed to have access to its private network ?
I don't think this is a problem we can solve in the capacity layer. This is something you need to figure out how to solve in the way you implement your service.

The `/var/lib/rancher/k3s/server/manifests` could maybe be something we allow user to define in their k8s workload, maybe...

**Comment by muhamadazmy** [comment]
Since k8s deployment is done over 2 stages 
- Install
- Run 

between the install and run we can actually mount the disk, and put the yaml files (that need to be add to the workload) then when the node starts, it runs the apply automatically
