### ISSUE TITLE
ZDB deployment fails with "failed to get network namespace"

### ISSUE THREAD

**Issue by OmarElawady** [threefoldtech/zos#933]
While installing ZDB instances to deploy MinIO. All ZDBs seemed to be working fine except the ones deployed on the node "3dAnxcykEDgKVQdTRKmktggL2MZbm3CPSdS9Tdoy4HAF", it failed thrice with the same error and the whole thing worked after blocking deployment on this node.

Error message: "failed to find IP address on zdb0 interface: failed to get an IP for interface zdb0: failed to get network namespace zdb-ns-d424458c: failed to Statfs "/var/run/netns/zdb-ns-d424458c": no such file or directory"

Workload ids: [480046](https://explorer.testnet.grid.tf/api/v1/reservations/workloads/480046) [480023](https://explorer.testnet.grid.tf/api/v1/reservations/workloads/480023) [479895](https://explorer.testnet.grid.tf/api/v1/reservations/workloads/479895)

The used script (after blocking): [code](https://gist.github.com/OmarElawady/ac67d8e4a7233c9bf1ade20789fd5e3f)

**Comment by muhamadazmy** [comment]
So i checked the affected node and have found the following:
- When doing `ip netns` we can see that the namespace `zdb-ns-d424458c`
- When listing running zdb containers, we find 2 zdb containers running, one of them (container 'zdb7e770496-3138-4200-93a6-e4e8857fce16') is using the namespace `/var/run/netns/zdb-ns-d424458c`

So the namespace was deleted while being used by this container. we notice the following:
- This namespace is using the old naming convention (random name of 8 characters)
- The only reason this namespace might have been deleted is (big chance) due to a manual clean up script 
that was used to clean up non-used old zdb netns.
- The other places where the network namespace is removed is after stopping the zdb container in case it's not serving any zdb namespaces anymore, which is not the case because this zdb container already has some namespaces configured

Current solution:
- I manually restored the network namespace for that zdb container on the node. this should fix the problem (please try again)

![image](https://user-images.githubusercontent.com/10920323/93193982-d6ff0f80-f747-11ea-8f98-d52e61b9dec6.png)

We will leave this issue open in case that was repeated on another node, in that case it's a real issue not related to the manual intervention done earlier

**Comment by OmarElawady** [comment]
I unblocked the node and retried and everything works fine now (one ZDB was deployed on it). Also the script has run multiple times and it picks 13 nodes from freefarm and Mazr3a and this is the only node that failed with this error.

**Comment by zaibon** [comment]
@OmarElawady so we can close this now ?

**Comment by OmarElawady** [comment]
Sure, I didn't face it again.
