### ISSUE TITLE
failed to create network resource for network 7wUMhkuNzw9aK

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/zos#950]
https://explorer.testnet.grid.tf/api/v1/reservations/workloads/485525

```
message: "failed to create network resource for network 7wUMhkuNzw9aK: failed to configure network resource: failed to configure wireguard interface: failed to bring wireguard interface w-7wUMhkuNzw9aK up: address already in use",
epoch: 1600691263,
node_id: "A7FmQZ72h7FzjkJMGXmzLDFyfyxzitDZYuernGG97nv7"
```

node A7FmQZ72h7FzjkJMGXmzLDFyfyxzitDZYuernGG97nv7 is having lots of failures too

**Comment by xmonader** [comment]
another one 
```
message: "failed to create network resource for network FvFk5W7BAHz1Z: failed to configure network resource: failed to configure wireguard interface: failed to bring wireguard interface w-FvFk5W7BAHz1Z up: address already in use",

```
https://explorer.testnet.grid.tf/api/v1/reservations/workloads/485714

node id: 72CP8QPhMSpF7MbSvNR1TYZFbTnbRiuyvq5xwcoRNAib

**Comment by xmonader** [comment]
https://explorer.testnet.grid.tf/api/v1/reservations/workloads/485841

node id 72CP8QPhMSpF7MbSvNR1TYZFbTnbRiuyvq5xwcoRNAib

**Comment by muhamadazmy** [comment]
After some investigation the problem seems to be that the network resources is trying to use a port that is already used on zos. For example, this reservation here https://explorer.testnet.grid.tf/api/v1/reservations/workloads/485525 is trying to use port `3356`. 

![image](https://user-images.githubusercontent.com/10920323/93863831-52227180-fcc4-11ea-8978-78aac2fe7203.png)

But the thing is, this port is not reported as used on the node info. So the question becomes, why the node ports on the explorer are not matching the ones used on the node.

Doing more investigations
