### ISSUE TITLE
2.2 upgrade issues (follow up)

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/zos#952]
Reservation: https://explorer.testnet.grid.tf/api/v1/reservations/workloads/485591
Error: message": "error starting container: invalid entrypoint definition ''",
—-
https://explorer.testnet.grid.tf/api/v1/reservations/workloads/485583
Error: "message": "error starting container: mkdir /run/containerd/io.containerd.runtime.v2.task/ns573/485583-1: file exists: unknown",
—-
Reservation: https://explorer.testnet.grid.tf/api/v1/reservations/workloads/485589
Error: "message": "error starting container: OCI runtime create failed: container_linux.go:346: starting container process caused \"exec: \\\"/start.sh\\\": stat /start.sh: no such file or directory\": unknown",
—-
Reservation: https://explorer.testnet.grid.tf/api/v1/reservations/workloads/485593
Error: "message": "error starting container: invalid entrypoint definition ''",

zos team found some problems with binaries upgraded and they're working on it

**Comment by muhamadazmy** [comment]
All this issue are caused by the same issue. 0-fs was not updated correctly on the nodes, while other daemons were depending on newer version of 0-fs.

The problem is this also caused update process to get stuck. Luckily we managed to push the correct 0-fs version to mainnet. But the update process is not complete yet. We need to create multiple minor release to do some clean up.

> I will also start a new an flist pkg manager solution to avoid such problems in the future.
