### ISSUE TITLE
Failed to create read-write subvolume for 0-fs: Not enough space left in pools of this type ssd

### ISSUE THREAD

**Issue by dmahmouali** [threefoldtech/zos#980]
- when I try to deploy 3Bot on https://deploy3bot.grid.tf/ get this error. 
- workload: https://explorer.grid.tf/api/v1/reservations/workloads/14077
- message: "failed to create read-write subvolume for 0-fs: Not enough space left in pools of this type ssd",
![image](https://user-images.githubusercontent.com/36021484/94465079-a4312e80-01bf-11eb-9ec3-7574fb52b3c0.png)

**Comment by DylanVerstraete** [comment]
This issue could be related to https://github.com/threefoldtech/zos/issues/709

I checked the node, it has only 1 SSD which is almost full:

![Screenshot from 2020-09-29 13-12-24](https://user-images.githubusercontent.com/17138347/94551320-75fe2e00-0255-11eb-97ab-8988d6e5480a.png)

As you can see in the screenshot it tries to provision this workload but if fails because the total size on disk would be larger than what it can hold. 

I think there are subvolumes on that disk which are not being used anymore and are not cleaned up from previous releases.

A PR is open: https://github.com/threefoldtech/zos/pull/883 but it requires more testing before we can think of releasing this on mainnet.

**Comment by DylanVerstraete** [comment]
Currently testing out the PR on devnet. Once we get good results we will release on testnet

**Comment by muhamadazmy** [comment]
This will be fixed on next release 0.4.7
